# generated by datamodel-codegen:
#   filename: openapi.json

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum, IntEnum
from typing import Any, Dict, Literal

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    PositiveFloat,
    RootModel,
    confloat,
    conint,
    constr,
)


class Model(Enum):
    bs = 'bs'
    heston = 'heston'
    sabr = 'sabr'
    jd = 'jd'
    vg = 'vg'
    binomial = 'binomial'
    pde = 'pde'
    fft = 'fft'
    mc = 'mc'
    localvol = 'localvol'
    barrier = 'barrier'
    asian = 'asian'
    lookback = 'lookback'
    digital = 'digital'
    compound = 'compound'
    chooser = 'chooser'
    multiasset = 'multiasset'


class SigmaSource(Enum):
    auto = 'auto'
    atmIv = 'atmIv'
    hv = 'hv'


class RateMode(Enum):
    matched = 'matched'
    fixedTenor = 'fixedTenor'


class RateTenor(Enum):
    field_1MO = '1MO'
    field_3MO = '3MO'
    field_6MO = '6MO'
    field_1Y = '1Y'
    field_2Y = '2Y'
    field_5Y = '5Y'
    field_10Y = '10Y'
    field_30Y = '30Y'


class SpotSource(Enum):
    snapshot = 'snapshot'


class Resolve(BaseModel):
    spot: bool | None = True
    sigma: bool | None = True
    sigmaSource: SigmaSource | None = 'auto'
    dividend: bool | None = True
    rate: bool | None = True
    rateMode: RateMode | None = 'matched'
    rateTenor: RateTenor | None = None
    tenor: bool | None = True
    spotSource: SpotSource | None = 'snapshot'
    calibration: bool | None = False


class Dividend(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    time: float | str | None = None
    amount: float | str | None = None


class ModelParams(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    dividends: list[Dividend] | None = Field(
        None,
        description='Discrete cash-dividend schedule for the binomial engine (model:"binomial"): a list of { time: years-to-ex-date (>0), amount: cash-per-share (>=0) }. Fixed cash amounts only (no proportional/escrowed mode). Continuous q is forced to 0 when a schedule is present, to avoid double-counting. Legacy aliases useDiscreteDividends / exDividendDates / dividendAmounts / dividendTimeUnit are also accepted; see the /v1/compute/price description.',
    )


class DayCount(Enum):
    calendar = 'calendar'
    trading = 'trading'


class Detail(Enum):
    summary = 'summary'
    distribution = 'distribution'
    full = 'full'


class PriceRequest1(BaseModel):
    model: Model | None = 'bs'
    isCall: bool
    K: PositiveFloat
    S: PositiveFloat | None = None
    r: float | None = None
    q: float | None = None
    sigma: confloat(ge=0.0) | None = None
    t: confloat(ge=0.0)
    symbol: constr(pattern=r'^[A-Za-z0-9./-]+$', min_length=1, max_length=20) | None = (
        None
    )
    expiry: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    expiration: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    resolve: Resolve | None = Field(
        {
            'spot': True,
            'sigma': True,
            'sigmaSource': 'auto',
            'dividend': True,
            'rate': True,
            'rateMode': 'matched',
            'tenor': True,
            'spotSource': 'snapshot',
            'calibration': False,
        },
        validate_default=True,
    )
    modelParams: ModelParams | None = None
    calibrationId: str | None = None
    steps: conint(ge=10, le=2000) | None = Field(
        None,
        description='Binomial step count (10..2000). Also accepted as modelParams.steps, which wins when both are supplied. When omitted, the dispatcher uses 200.',
    )
    isAmerican: bool | None = Field(
        None,
        description='American exercise. Also accepted as modelParams.isAmerican / modelParams.enableAmerican, which win when both are supplied. When omitted, the dispatcher prices European.',
    )
    dayCount: DayCount | None = Field(
        None,
        description='Day-count basis for the per-day Greeks (theta, charm, veta, color, dcharmDvol). `calendar` divides by 365 calendar days and is the default when omitted; `trading` divides by 252 trading days, making those five Greeks 365/252 (about 1.448x) larger. The other twelve Greeks are unaffected.',
    )
    detail: Detail | None = None
    histogramBins: conint(ge=2, le=200) | None = None


class Resolve1(BaseModel):
    spot: bool | None = True
    sigma: bool | None = True
    sigmaSource: SigmaSource | None = 'auto'
    dividend: bool | None = True
    rate: bool | None = True
    rateMode: RateMode | None = 'matched'
    rateTenor: RateTenor | None = None
    tenor: bool | None = True
    spotSource: SpotSource | None = 'snapshot'
    calibration: bool | None = False


class ModelParams1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    dividends: list[Dividend] | None = Field(
        None,
        description='Discrete cash-dividend schedule for the binomial engine (model:"binomial"): a list of { time: years-to-ex-date (>0), amount: cash-per-share (>=0) }. Fixed cash amounts only (no proportional/escrowed mode). Continuous q is forced to 0 when a schedule is present, to avoid double-counting. Legacy aliases useDiscreteDividends / exDividendDates / dividendAmounts / dividendTimeUnit are also accepted; see the /v1/compute/price description.',
    )


class PriceRequest2(BaseModel):
    model: Model | None = 'bs'
    isCall: bool
    K: PositiveFloat
    S: PositiveFloat | None = None
    r: float | None = None
    q: float | None = None
    sigma: confloat(ge=0.0) | None = None
    t: confloat(ge=0.0) | None = None
    symbol: constr(pattern=r'^[A-Za-z0-9./-]+$', min_length=1, max_length=20) | None = (
        None
    )
    expiry: constr(pattern=r'^\d{4}-\d{2}-\d{2}$')
    expiration: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    resolve: Resolve1 | None = Field(
        {
            'spot': True,
            'sigma': True,
            'sigmaSource': 'auto',
            'dividend': True,
            'rate': True,
            'rateMode': 'matched',
            'tenor': True,
            'spotSource': 'snapshot',
            'calibration': False,
        },
        validate_default=True,
    )
    modelParams: ModelParams1 | None = None
    calibrationId: str | None = None
    steps: conint(ge=10, le=2000) | None = Field(
        None,
        description='Binomial step count (10..2000). Also accepted as modelParams.steps, which wins when both are supplied. When omitted, the dispatcher uses 200.',
    )
    isAmerican: bool | None = Field(
        None,
        description='American exercise. Also accepted as modelParams.isAmerican / modelParams.enableAmerican, which win when both are supplied. When omitted, the dispatcher prices European.',
    )
    dayCount: DayCount | None = Field(
        None,
        description='Day-count basis for the per-day Greeks (theta, charm, veta, color, dcharmDvol). `calendar` divides by 365 calendar days and is the default when omitted; `trading` divides by 252 trading days, making those five Greeks 365/252 (about 1.448x) larger. The other twelve Greeks are unaffected.',
    )
    detail: Detail | None = None
    histogramBins: conint(ge=2, le=200) | None = None


class Resolve2(BaseModel):
    spot: bool | None = True
    sigma: bool | None = True
    sigmaSource: SigmaSource | None = 'auto'
    dividend: bool | None = True
    rate: bool | None = True
    rateMode: RateMode | None = 'matched'
    rateTenor: RateTenor | None = None
    tenor: bool | None = True
    spotSource: SpotSource | None = 'snapshot'
    calibration: bool | None = False


class ModelParams2(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    dividends: list[Dividend] | None = Field(
        None,
        description='Discrete cash-dividend schedule for the binomial engine (model:"binomial"): a list of { time: years-to-ex-date (>0), amount: cash-per-share (>=0) }. Fixed cash amounts only (no proportional/escrowed mode). Continuous q is forced to 0 when a schedule is present, to avoid double-counting. Legacy aliases useDiscreteDividends / exDividendDates / dividendAmounts / dividendTimeUnit are also accepted; see the /v1/compute/price description.',
    )


class PriceRequest3(BaseModel):
    model: Model | None = 'bs'
    isCall: bool
    K: PositiveFloat
    S: PositiveFloat | None = None
    r: float | None = None
    q: float | None = None
    sigma: confloat(ge=0.0) | None = None
    t: confloat(ge=0.0) | None = None
    symbol: constr(pattern=r'^[A-Za-z0-9./-]+$', min_length=1, max_length=20) | None = (
        None
    )
    expiry: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    expiration: constr(pattern=r'^\d{4}-\d{2}-\d{2}$')
    resolve: Resolve2 | None = Field(
        {
            'spot': True,
            'sigma': True,
            'sigmaSource': 'auto',
            'dividend': True,
            'rate': True,
            'rateMode': 'matched',
            'tenor': True,
            'spotSource': 'snapshot',
            'calibration': False,
        },
        validate_default=True,
    )
    modelParams: ModelParams2 | None = None
    calibrationId: str | None = None
    steps: conint(ge=10, le=2000) | None = Field(
        None,
        description='Binomial step count (10..2000). Also accepted as modelParams.steps, which wins when both are supplied. When omitted, the dispatcher uses 200.',
    )
    isAmerican: bool | None = Field(
        None,
        description='American exercise. Also accepted as modelParams.isAmerican / modelParams.enableAmerican, which win when both are supplied. When omitted, the dispatcher prices European.',
    )
    dayCount: DayCount | None = Field(
        None,
        description='Day-count basis for the per-day Greeks (theta, charm, veta, color, dcharmDvol). `calendar` divides by 365 calendar days and is the default when omitted; `trading` divides by 252 trading days, making those five Greeks 365/252 (about 1.448x) larger. The other twelve Greeks are unaffected.',
    )
    detail: Detail | None = None
    histogramBins: conint(ge=2, le=200) | None = None


class PriceRequest(RootModel[PriceRequest1 | PriceRequest2 | PriceRequest3]):
    root: PriceRequest1 | PriceRequest2 | PriceRequest3


class Resolve3(BaseModel):
    spot: bool | None = True
    sigma: bool | None = True
    sigmaSource: SigmaSource | None = 'auto'
    dividend: bool | None = True
    rate: bool | None = True
    rateMode: RateMode | None = 'matched'
    rateTenor: RateTenor | None = None
    tenor: bool | None = True
    spotSource: SpotSource | None = 'snapshot'
    calibration: bool | None = False


class ModelParams3(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    dividends: list[Dividend] | None = Field(
        None,
        description='Discrete cash-dividend schedule for the binomial engine (model:"binomial"): a list of { time: years-to-ex-date (>0), amount: cash-per-share (>=0) }. Fixed cash amounts only (no proportional/escrowed mode). Continuous q is forced to 0 when a schedule is present, to avoid double-counting. Legacy aliases useDiscreteDividends / exDividendDates / dividendAmounts / dividendTimeUnit are also accepted; see the /v1/compute/price description.',
    )


class GreeksRequest1(BaseModel):
    model: Model | None = 'bs'
    isCall: bool
    K: PositiveFloat
    S: PositiveFloat | None = None
    r: float | None = None
    q: float | None = None
    sigma: confloat(ge=0.0) | None = None
    t: confloat(ge=0.0)
    symbol: constr(pattern=r'^[A-Za-z0-9./-]+$', min_length=1, max_length=20) | None = (
        None
    )
    expiry: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    expiration: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    resolve: Resolve3 | None = Field(
        {
            'spot': True,
            'sigma': True,
            'sigmaSource': 'auto',
            'dividend': True,
            'rate': True,
            'rateMode': 'matched',
            'tenor': True,
            'spotSource': 'snapshot',
            'calibration': False,
        },
        validate_default=True,
    )
    modelParams: ModelParams3 | None = None
    calibrationId: str | None = None
    includeInsight: bool | None = False
    steps: conint(ge=10, le=2000) | None = Field(
        None,
        description='Binomial step count (10..2000). Also accepted as modelParams.steps, which wins when both are supplied. When omitted, the dispatcher uses 200.',
    )
    isAmerican: bool | None = Field(
        None,
        description='American exercise. Also accepted as modelParams.isAmerican / modelParams.enableAmerican, which win when both are supplied. When omitted, the dispatcher prices European.',
    )
    dayCount: DayCount | None = Field(
        None,
        description='Day-count basis for the per-day Greeks (theta, charm, veta, color, dcharmDvol). `calendar` divides by 365 calendar days and is the default when omitted; `trading` divides by 252 trading days, making those five Greeks 365/252 (about 1.448x) larger. The other twelve Greeks are unaffected.',
    )


class Resolve4(BaseModel):
    spot: bool | None = True
    sigma: bool | None = True
    sigmaSource: SigmaSource | None = 'auto'
    dividend: bool | None = True
    rate: bool | None = True
    rateMode: RateMode | None = 'matched'
    rateTenor: RateTenor | None = None
    tenor: bool | None = True
    spotSource: SpotSource | None = 'snapshot'
    calibration: bool | None = False


class ModelParams4(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    dividends: list[Dividend] | None = Field(
        None,
        description='Discrete cash-dividend schedule for the binomial engine (model:"binomial"): a list of { time: years-to-ex-date (>0), amount: cash-per-share (>=0) }. Fixed cash amounts only (no proportional/escrowed mode). Continuous q is forced to 0 when a schedule is present, to avoid double-counting. Legacy aliases useDiscreteDividends / exDividendDates / dividendAmounts / dividendTimeUnit are also accepted; see the /v1/compute/price description.',
    )


class GreeksRequest2(BaseModel):
    model: Model | None = 'bs'
    isCall: bool
    K: PositiveFloat
    S: PositiveFloat | None = None
    r: float | None = None
    q: float | None = None
    sigma: confloat(ge=0.0) | None = None
    t: confloat(ge=0.0) | None = None
    symbol: constr(pattern=r'^[A-Za-z0-9./-]+$', min_length=1, max_length=20) | None = (
        None
    )
    expiry: constr(pattern=r'^\d{4}-\d{2}-\d{2}$')
    expiration: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    resolve: Resolve4 | None = Field(
        {
            'spot': True,
            'sigma': True,
            'sigmaSource': 'auto',
            'dividend': True,
            'rate': True,
            'rateMode': 'matched',
            'tenor': True,
            'spotSource': 'snapshot',
            'calibration': False,
        },
        validate_default=True,
    )
    modelParams: ModelParams4 | None = None
    calibrationId: str | None = None
    includeInsight: bool | None = False
    steps: conint(ge=10, le=2000) | None = Field(
        None,
        description='Binomial step count (10..2000). Also accepted as modelParams.steps, which wins when both are supplied. When omitted, the dispatcher uses 200.',
    )
    isAmerican: bool | None = Field(
        None,
        description='American exercise. Also accepted as modelParams.isAmerican / modelParams.enableAmerican, which win when both are supplied. When omitted, the dispatcher prices European.',
    )
    dayCount: DayCount | None = Field(
        None,
        description='Day-count basis for the per-day Greeks (theta, charm, veta, color, dcharmDvol). `calendar` divides by 365 calendar days and is the default when omitted; `trading` divides by 252 trading days, making those five Greeks 365/252 (about 1.448x) larger. The other twelve Greeks are unaffected.',
    )


class Resolve5(BaseModel):
    spot: bool | None = True
    sigma: bool | None = True
    sigmaSource: SigmaSource | None = 'auto'
    dividend: bool | None = True
    rate: bool | None = True
    rateMode: RateMode | None = 'matched'
    rateTenor: RateTenor | None = None
    tenor: bool | None = True
    spotSource: SpotSource | None = 'snapshot'
    calibration: bool | None = False


class ModelParams5(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    dividends: list[Dividend] | None = Field(
        None,
        description='Discrete cash-dividend schedule for the binomial engine (model:"binomial"): a list of { time: years-to-ex-date (>0), amount: cash-per-share (>=0) }. Fixed cash amounts only (no proportional/escrowed mode). Continuous q is forced to 0 when a schedule is present, to avoid double-counting. Legacy aliases useDiscreteDividends / exDividendDates / dividendAmounts / dividendTimeUnit are also accepted; see the /v1/compute/price description.',
    )


class GreeksRequest3(BaseModel):
    model: Model | None = 'bs'
    isCall: bool
    K: PositiveFloat
    S: PositiveFloat | None = None
    r: float | None = None
    q: float | None = None
    sigma: confloat(ge=0.0) | None = None
    t: confloat(ge=0.0) | None = None
    symbol: constr(pattern=r'^[A-Za-z0-9./-]+$', min_length=1, max_length=20) | None = (
        None
    )
    expiry: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    expiration: constr(pattern=r'^\d{4}-\d{2}-\d{2}$')
    resolve: Resolve5 | None = Field(
        {
            'spot': True,
            'sigma': True,
            'sigmaSource': 'auto',
            'dividend': True,
            'rate': True,
            'rateMode': 'matched',
            'tenor': True,
            'spotSource': 'snapshot',
            'calibration': False,
        },
        validate_default=True,
    )
    modelParams: ModelParams5 | None = None
    calibrationId: str | None = None
    includeInsight: bool | None = False
    steps: conint(ge=10, le=2000) | None = Field(
        None,
        description='Binomial step count (10..2000). Also accepted as modelParams.steps, which wins when both are supplied. When omitted, the dispatcher uses 200.',
    )
    isAmerican: bool | None = Field(
        None,
        description='American exercise. Also accepted as modelParams.isAmerican / modelParams.enableAmerican, which win when both are supplied. When omitted, the dispatcher prices European.',
    )
    dayCount: DayCount | None = Field(
        None,
        description='Day-count basis for the per-day Greeks (theta, charm, veta, color, dcharmDvol). `calendar` divides by 365 calendar days and is the default when omitted; `trading` divides by 252 trading days, making those five Greeks 365/252 (about 1.448x) larger. The other twelve Greeks are unaffected.',
    )


class GreeksRequest(RootModel[GreeksRequest1 | GreeksRequest2 | GreeksRequest3]):
    root: GreeksRequest1 | GreeksRequest2 | GreeksRequest3


class Strike(BaseModel):
    strike_cents: float
    stk_px_cents: float
    c_oi: float
    p_oi: float
    gamma: float
    delta: float | None = None
    vega: float | None = None
    smooth_smv_vol: float | None = None
    c_mid_iv: float | None = None
    p_mid_iv: float | None = None
    yte: float | None = None
    expir_date: str | None = None


class Resolve6(BaseModel):
    spot: bool | None = True
    sigma: bool | None = True
    sigmaSource: SigmaSource | None = 'auto'
    dividend: bool | None = True
    rate: bool | None = True
    rateMode: RateMode | None = 'matched'
    rateTenor: RateTenor | None = None
    tenor: bool | None = True
    spotSource: SpotSource | None = 'snapshot'
    calibration: bool | None = False


class ExposureRequest(BaseModel):
    strikes: list[Strike] = Field(..., max_length=5000, min_length=1)
    spotPrice: PositiveFloat | None = None
    riskFreeRate: float | None = None
    dividendYield: float | None = None
    symbol: constr(pattern=r'^[A-Za-z0-9./-]+$', min_length=1, max_length=20) | None = (
        None
    )
    expiry: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    expiration: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    resolve: Resolve6 | None = Field(
        {
            'spot': True,
            'sigma': True,
            'sigmaSource': 'auto',
            'dividend': True,
            'rate': True,
            'rateMode': 'matched',
            'tenor': True,
            'spotSource': 'snapshot',
            'calibration': False,
        },
        validate_default=True,
    )
    wallMaxDte: float | None = None


class Resolve7(BaseModel):
    spot: bool | None = True
    sigma: bool | None = True
    sigmaSource: SigmaSource | None = 'auto'
    dividend: bool | None = True
    rate: bool | None = True
    rateMode: RateMode | None = 'matched'
    rateTenor: RateTenor | None = None
    tenor: bool | None = True
    spotSource: SpotSource | None = 'snapshot'
    calibration: bool | None = False


class Model6(Enum):
    bs = 'bs'
    binomial = 'binomial'


class ModelParams6(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    dividends: list[Dividend] | None = Field(
        None,
        description='Discrete cash-dividend schedule for the binomial engine (model:"binomial"): a list of { time: years-to-ex-date (>0), amount: cash-per-share (>=0) }. Fixed cash amounts only (no proportional/escrowed mode). Continuous q is forced to 0 when a schedule is present, to avoid double-counting. Legacy aliases useDiscreteDividends / exDividendDates / dividendAmounts / dividendTimeUnit are also accepted; see the /v1/compute/price description.',
    )


class ScenarioRequest(BaseModel):
    isCall: bool
    S: PositiveFloat | None = None
    K: PositiveFloat
    r: float | None = None
    q: float | None = None
    sigma: confloat(ge=0.0) | None = None
    t: confloat(ge=0.0) | None = None
    symbol: constr(pattern=r'^[A-Za-z0-9./-]+$', min_length=1, max_length=20) | None = (
        None
    )
    expiry: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    expiration: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    resolve: Resolve7 | None = Field(
        {
            'spot': True,
            'sigma': True,
            'sigmaSource': 'auto',
            'dividend': True,
            'rate': True,
            'rateMode': 'matched',
            'tenor': True,
            'spotSource': 'snapshot',
            'calibration': False,
        },
        validate_default=True,
    )
    spotChanges: list[float] = Field(..., max_length=20, min_length=2)
    volChanges: list[float] = Field(..., max_length=20, min_length=2)
    model: Model6 | None = None
    modelParams: ModelParams6 | None = None
    steps: conint(ge=10, le=2000) | None = Field(
        None,
        description='Binomial step count (10..2000) for model:"binomial". Also accepted as modelParams.steps, which wins when both are supplied. Defaults to 200 when omitted.',
    )
    isAmerican: bool | None = Field(
        None,
        description='American exercise for model:"binomial". Also accepted as modelParams.isAmerican / modelParams.enableAmerican, which win when both are supplied. Defaults to European when omitted.',
    )


class Resolve8(BaseModel):
    spot: bool | None = True
    sigma: bool | None = True
    sigmaSource: SigmaSource | None = 'auto'
    dividend: bool | None = True
    rate: bool | None = True
    rateMode: RateMode | None = 'matched'
    rateTenor: RateTenor | None = None
    tenor: bool | None = True
    spotSource: SpotSource | None = 'snapshot'
    calibration: bool | None = False


class Axis(Enum):
    spot = 'spot'
    time = 'time'
    volatility = 'volatility'


class Model7(Enum):
    bs = 'bs'
    heston = 'heston'
    binomial = 'binomial'


class ModelParams7(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    dividends: list[Dividend] | None = Field(
        None,
        description='Discrete cash-dividend schedule for the binomial engine (model:"binomial"): a list of { time: years-to-ex-date (>0), amount: cash-per-share (>=0) }. Fixed cash amounts only (no proportional/escrowed mode). Continuous q is forced to 0 when a schedule is present, to avoid double-counting. Legacy aliases useDiscreteDividends / exDividendDates / dividendAmounts / dividendTimeUnit are also accepted; see the /v1/compute/price description.',
    )


class Greek(Enum):
    price = 'price'
    delta = 'delta'
    gamma = 'gamma'
    vega = 'vega'
    theta = 'theta'
    rho = 'rho'
    vanna = 'vanna'
    charm = 'charm'
    vomma = 'vomma'
    veta = 'veta'
    speed = 'speed'
    zomma = 'zomma'
    color = 'color'
    ultima = 'ultima'
    lambda_ = 'lambda'
    epsilon = 'epsilon'
    phi = 'phi'
    dcharmDvol = 'dcharmDvol'


class SensitivityRequest(BaseModel):
    isCall: bool
    S: PositiveFloat | None = None
    K: PositiveFloat
    r: float | None = None
    q: float | None = None
    sigma: confloat(ge=0.0) | None = None
    t: confloat(ge=0.0) | None = None
    symbol: constr(pattern=r'^[A-Za-z0-9./-]+$', min_length=1, max_length=20) | None = (
        None
    )
    expiry: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    expiration: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    resolve: Resolve8 | None = Field(
        {
            'spot': True,
            'sigma': True,
            'sigmaSource': 'auto',
            'dividend': True,
            'rate': True,
            'rateMode': 'matched',
            'tenor': True,
            'spotSource': 'snapshot',
            'calibration': False,
        },
        validate_default=True,
    )
    axis: Axis
    points: conint(ge=5, le=200) | None = 50
    spotMin: PositiveFloat | None = None
    spotMax: PositiveFloat | None = None
    daysToExpiry: PositiveFloat | None = None
    volMin: confloat(ge=0.0) | None = None
    volMax: PositiveFloat | None = None
    model: Model7 | None = 'bs'
    modelParams: ModelParams7 | None = None
    steps: conint(ge=10, le=2000) | None = Field(
        None,
        description='Binomial step count (10..2000) for model:"binomial" sweeps. Also accepted as modelParams.steps, which wins when both are supplied. Defaults to 200 when omitted.',
    )
    isAmerican: bool | None = Field(
        None,
        description='American exercise for model:"binomial" sweeps. Also accepted as modelParams.isAmerican / modelParams.enableAmerican, which win when both are supplied. Defaults to European when omitted.',
    )
    greeks: list[Greek] | None = Field(None, max_length=20)
    dayCount: DayCount | None = Field(
        None,
        description='Day-count basis for the per-day Greeks (theta, charm, veta, color, dcharmDvol), matching /v1/compute/greeks. `calendar` divides by 365 calendar days and is the default when omitted; `trading` divides by 252 trading days. The other twelve Greeks are unaffected.',
    )


class Resolve9(BaseModel):
    spot: bool | None = True
    sigma: bool | None = True
    sigmaSource: SigmaSource | None = 'auto'
    dividend: bool | None = True
    rate: bool | None = True
    rateMode: RateMode | None = 'matched'
    rateTenor: RateTenor | None = None
    tenor: bool | None = True
    spotSource: SpotSource | None = 'snapshot'
    calibration: bool | None = False


class Type(Enum):
    call = 'call'
    put = 'put'
    stock = 'stock'


class Side(Enum):
    long = 'long'
    short = 'short'


class Model8(Enum):
    bs = 'bs'
    binomial = 'binomial'


class ModelParams8(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    dividends: list[Dividend] | None = Field(
        None,
        description='Discrete cash-dividend schedule for the binomial engine (model:"binomial"): a list of { time: years-to-ex-date (>0), amount: cash-per-share (>=0) }. Fixed cash amounts only (no proportional/escrowed mode). Continuous q is forced to 0 when a schedule is present, to avoid double-counting. Legacy aliases useDiscreteDividends / exDividendDates / dividendAmounts / dividendTimeUnit are also accepted; see the /v1/compute/price description.',
    )


class Leg(BaseModel):
    type: Type
    side: Side
    quantity: PositiveFloat | None = 1
    strike: PositiveFloat | None = None
    premium: confloat(ge=0.0) | None = None
    costBasis: confloat(ge=0.0) | None = None
    sigma: confloat(ge=0.0) | None = None
    t: confloat(ge=0.0) | None = None
    model: Model8 | None = None
    isAmerican: bool | None = None
    steps: conint(ge=10, le=2000) | None = None
    modelParams: ModelParams8 | None = None


class StrategyRequest(BaseModel):
    S: PositiveFloat | None = None
    r: float | None = None
    q: float | None = None
    sigma: confloat(ge=0.0) | None = None
    t: confloat(ge=0.0) | None = None
    symbol: constr(pattern=r'^[A-Za-z0-9./-]+$', min_length=1, max_length=20) | None = (
        None
    )
    expiry: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    expiration: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    resolve: Resolve9 | None = Field(
        {
            'spot': True,
            'sigma': True,
            'sigmaSource': 'auto',
            'dividend': True,
            'rate': True,
            'rateMode': 'matched',
            'tenor': True,
            'spotSource': 'snapshot',
            'calibration': False,
        },
        validate_default=True,
    )
    legs: list[Leg] = Field(..., max_length=10, min_length=1)
    numPoints: conint(ge=10, le=500) | None = None
    priceRangePct: confloat(le=2.0, gt=0.0) | None = None


class Strike1(BaseModel):
    strike: PositiveFloat
    callOI: confloat(ge=0.0)
    putOI: confloat(ge=0.0)


class MaxPainRequest(BaseModel):
    strikes: list[Strike1] = Field(..., max_length=5000, min_length=1)


class Resolve10(BaseModel):
    spot: bool | None = True
    sigma: bool | None = True
    sigmaSource: SigmaSource | None = 'auto'
    dividend: bool | None = True
    rate: bool | None = True
    rateMode: RateMode | None = 'matched'
    rateTenor: RateTenor | None = None
    tenor: bool | None = True
    spotSource: SpotSource | None = 'snapshot'
    calibration: bool | None = False


class ExpectedMoveRequest1(BaseModel):
    spotPrice: PositiveFloat | None = None
    strikePrice: PositiveFloat | None = None
    riskFreeRate: float | None = None
    dividendYield: float | None = None
    atmIV: PositiveFloat
    daysToExpiry: PositiveFloat | None = None
    atmCallPrice: confloat(ge=0.0) | None = None
    atmPutPrice: confloat(ge=0.0) | None = None
    symbol: constr(pattern=r'^[A-Za-z0-9./-]+$', min_length=1, max_length=20) | None = (
        None
    )
    expiry: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    expiration: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    resolve: Resolve10 | None = Field(
        {
            'spot': True,
            'sigma': True,
            'sigmaSource': 'auto',
            'dividend': True,
            'rate': True,
            'rateMode': 'matched',
            'tenor': True,
            'spotSource': 'snapshot',
            'calibration': False,
        },
        validate_default=True,
    )
    atmIv: PositiveFloat | None = Field(
        None,
        description='Alias for `atmIV`. Accepted so callers can pipe the `atmIv` field from /v1/data/metrics/{symbol} or /v1/data/snapshot/{symbol} directly.',
    )


class Resolve11(BaseModel):
    spot: bool | None = True
    sigma: bool | None = True
    sigmaSource: SigmaSource | None = 'auto'
    dividend: bool | None = True
    rate: bool | None = True
    rateMode: RateMode | None = 'matched'
    rateTenor: RateTenor | None = None
    tenor: bool | None = True
    spotSource: SpotSource | None = 'snapshot'
    calibration: bool | None = False


class ExpectedMoveRequest2(BaseModel):
    spotPrice: PositiveFloat | None = None
    strikePrice: PositiveFloat | None = None
    riskFreeRate: float | None = None
    dividendYield: float | None = None
    atmIV: PositiveFloat | None = None
    daysToExpiry: PositiveFloat | None = None
    atmCallPrice: confloat(ge=0.0) | None = None
    atmPutPrice: confloat(ge=0.0) | None = None
    symbol: constr(pattern=r'^[A-Za-z0-9./-]+$', min_length=1, max_length=20) | None = (
        None
    )
    expiry: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    expiration: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    resolve: Resolve11 | None = Field(
        {
            'spot': True,
            'sigma': True,
            'sigmaSource': 'auto',
            'dividend': True,
            'rate': True,
            'rateMode': 'matched',
            'tenor': True,
            'spotSource': 'snapshot',
            'calibration': False,
        },
        validate_default=True,
    )
    atmIv: PositiveFloat = Field(
        ...,
        description='Alias for `atmIV`. Accepted so callers can pipe the `atmIv` field from /v1/data/metrics/{symbol} or /v1/data/snapshot/{symbol} directly.',
    )


class Resolve12(BaseModel):
    spot: bool | None = True
    sigma: bool | None = True
    sigmaSource: SigmaSource | None = 'auto'
    dividend: bool | None = True
    rate: bool | None = True
    rateMode: RateMode | None = 'matched'
    rateTenor: RateTenor | None = None
    tenor: bool | None = True
    spotSource: SpotSource | None = 'snapshot'
    calibration: bool | None = False


class ExpectedMoveRequest3(BaseModel):
    spotPrice: PositiveFloat | None = None
    strikePrice: PositiveFloat | None = None
    riskFreeRate: float | None = None
    dividendYield: float | None = None
    atmIV: PositiveFloat | None = None
    daysToExpiry: PositiveFloat | None = None
    atmCallPrice: confloat(ge=0.0)
    atmPutPrice: confloat(ge=0.0)
    symbol: constr(pattern=r'^[A-Za-z0-9./-]+$', min_length=1, max_length=20) | None = (
        None
    )
    expiry: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    expiration: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    resolve: Resolve12 | None = Field(
        {
            'spot': True,
            'sigma': True,
            'sigmaSource': 'auto',
            'dividend': True,
            'rate': True,
            'rateMode': 'matched',
            'tenor': True,
            'spotSource': 'snapshot',
            'calibration': False,
        },
        validate_default=True,
    )
    atmIv: PositiveFloat | None = Field(
        None,
        description='Alias for `atmIV`. Accepted so callers can pipe the `atmIv` field from /v1/data/metrics/{symbol} or /v1/data/snapshot/{symbol} directly.',
    )


class ExpectedMoveRequest(
    RootModel[ExpectedMoveRequest1 | ExpectedMoveRequest2 | ExpectedMoveRequest3]
):
    root: ExpectedMoveRequest1 | ExpectedMoveRequest2 | ExpectedMoveRequest3


class Strike2(RootModel[PositiveFloat]):
    root: PositiveFloat


class Iv(RootModel[PositiveFloat]):
    root: PositiveFloat


class Resolve13(BaseModel):
    spot: bool | None = True
    sigma: bool | None = True
    sigmaSource: SigmaSource | None = 'auto'
    dividend: bool | None = True
    rate: bool | None = True
    rateMode: RateMode | None = 'matched'
    rateTenor: RateTenor | None = None
    tenor: bool | None = True
    spotSource: SpotSource | None = 'snapshot'
    calibration: bool | None = False


class ProbabilityRequest1(BaseModel):
    mode: Literal['simple'] = 'simple'
    spotPrice: PositiveFloat | None = None
    strikes: list[Strike2] = Field(..., max_length=500, min_length=5)
    ivs: list[Iv] = Field(..., max_length=500, min_length=5)
    riskFreeRate: float | None = None
    dividendYield: float | None = None
    timeToExpiry: PositiveFloat | None = None
    symbol: constr(pattern=r'^[A-Za-z0-9./-]+$', min_length=1, max_length=20) | None = (
        None
    )
    expiry: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    expiration: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    resolve: Resolve13 | None = Field(
        {
            'spot': True,
            'sigma': True,
            'sigmaSource': 'auto',
            'dividend': True,
            'rate': True,
            'rateMode': 'matched',
            'tenor': True,
            'spotSource': 'snapshot',
            'calibration': False,
        },
        validate_default=True,
    )


class Resolve14(BaseModel):
    spot: bool | None = True
    sigma: bool | None = True
    sigmaSource: SigmaSource | None = 'auto'
    dividend: bool | None = True
    rate: bool | None = True
    rateMode: RateMode | None = 'matched'
    rateTenor: RateTenor | None = None
    tenor: bool | None = True
    spotSource: SpotSource | None = 'snapshot'
    calibration: bool | None = False


class ProbabilityRequest2(BaseModel):
    mode: Literal['full']
    symbol: constr(pattern=r'^[A-Za-z0-9./-]+$', min_length=1, max_length=20)
    expiration: str | None = None
    expiry: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    resolve: Resolve14 | None = Field(
        {
            'spot': True,
            'sigma': True,
            'sigmaSource': 'auto',
            'dividend': True,
            'rate': True,
            'rateMode': 'matched',
            'tenor': True,
            'spotSource': 'snapshot',
            'calibration': False,
        },
        validate_default=True,
    )
    riskFreeRate: float | None = None
    dividendYield: float | None = None


class ProbabilityRequest(RootModel[ProbabilityRequest1 | ProbabilityRequest2]):
    root: ProbabilityRequest1 | ProbabilityRequest2


class Model9(Enum):
    heston = 'heston'
    sabr = 'sabr'
    vg = 'vg'
    jd = 'jd'
    localvol = 'localvol'


class CalibrateRequest(BaseModel):
    model: Model9 = Field(..., description='Model to calibrate')
    symbol: str = Field(..., description='Ticker symbol (e.g. "SPY")')
    expiration: str | None = Field(
        None,
        description='Optional: specific expiration date (YYYY-MM-DD). Defaults to nearest.',
    )
    riskFreeRate: float | None = Field(
        None,
        description='Optional risk-free rate used during calibration. When omitted, the API resolves it from stored market data; unresolved requests return 422 rather than using a fabricated default.',
    )
    dividendYield: float | None = Field(
        None,
        description='Optional continuous dividend yield used during calibration. When omitted, the API resolves it from stored market data; unresolved requests return 422 rather than using a fabricated default.',
    )
    modelParams: dict[str, Any] | None = Field(
        None,
        description='Model-specific calibration options. Supported keys by model:\n\n**heston:** `accuracyMode` ("fast" | "balanced" | "precise", default "balanced")\n\n**sabr:** `fixBeta` (boolean, default true), `accuracyMode` ("fast" | "balanced" | "precise")\n\n**jd:** `modelType` / `jdModel` ("kou" | "merton" | "bates", default "kou")\n\n**vg / localvol:** no extra options',
    )


class ResolvedInputs(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    isCall: bool
    S: float = Field(..., description='Spot price')
    K: float = Field(..., description='Strike price')
    r: float = Field(..., description='Risk-free rate (decimal)')
    q: float = Field(..., description='Dividend yield (decimal)')
    sigma: float = Field(..., description='Volatility (decimal)')
    t: float = Field(..., description='Time to expiry (years)')
    modelParams: dict[str, Any] | None = Field(
        None, description='Model-specific knobs supplied or filled in by calibration'
    )
    calibrationId: str | None = Field(
        None,
        description='30-second in-memory handle returned by /v1/compute/calibrate. Persist `modelParams` for durable reuse.',
    )


class ResolvedSummary1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    value: float
    source: str


class ResolvedSummary(RootModel[dict[str, ResolvedSummary1]]):
    root: dict[str, ResolvedSummary1]


class McStats(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    stdError: float = Field(..., description='Standard error of the price estimate.')
    ciLow: float = Field(
        ..., description='Lower bound of the 95% confidence interval for the price.'
    )
    ciHigh: float = Field(
        ..., description='Upper bound of the 95% confidence interval for the price.'
    )
    nPaths: int = Field(
        ...,
        description='Effective number of paths the estimate was built from. With antithetic variates enabled this is up to 2× the requested `nPaths`.',
    )


class Percentiles(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    p1: float
    p5: float
    p10: float
    p25: float
    p50: float = Field(..., description='Median.')
    p75: float
    p90: float
    p95: float
    p99: float


class Histogram(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    binEdges: list[float]
    counts: list[int]


class McDistribution(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    count: int = Field(
        ..., description='Number of simulated paths the distribution was built from.'
    )
    mean: float = Field(..., description='Mean of the simulated terminal price.')
    min: float = Field(..., description='Minimum simulated terminal price.')
    max: float = Field(..., description='Maximum simulated terminal price.')
    percentiles: Percentiles = Field(
        ...,
        description='Linearly-interpolated percentiles of the simulated terminal price.',
    )
    histogram: Histogram = Field(
        ...,
        description='Equal-width histogram. `binEdges` length is `counts.length + 1`; bin `i` covers `[binEdges[i], binEdges[i+1])`. Bin count is configurable up to a server-enforced cap of 200; default 50.',
    )


class ExoticInsightMetric(BaseModel):
    label: str
    value: str
    rawValue: float
    highlight: bool | None = None


class VerdictType(Enum):
    positive = 'positive'
    negative = 'negative'
    neutral = 'neutral'


class ExoticInsight(BaseModel):
    model: str
    title: str
    subtitle: str
    accentColor: str
    metrics: list[ExoticInsightMetric]
    verdict: str
    verdictType: VerdictType


class GreeksResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    model: str
    price: float
    delta: float | None = Field(None, description='dP/dS')
    vega: float | None = Field(None, description='dP/dσ (per 1% vol change)')
    theta: float | None = Field(None, description='dP/dt (per day - see `dayCount`)')
    rho: float | None = Field(None, description='dP/dr (per 1% rate change)')
    epsilon: float | None = Field(
        None, description='dP/dq (per 1% dividend yield change)'
    )
    gamma: float | None = Field(None, description='d²P/dS²')
    vanna: float | None = Field(None, description='d²P/dSdσ')
    charm: float | None = Field(
        None, description='d²P/dSdt (delta decay, PER DAY - see `dayCount`)'
    )
    vomma: float | None = Field(None, description='d²P/dσ² (vega convexity)')
    veta: float | None = Field(
        None,
        description='d²P/dσdt (vega decay, per 1% vol change PER DAY - see `dayCount`)',
    )
    speed: float | None = Field(None, description='d³P/dS³ (gamma sensitivity to spot)')
    zomma: float | None = Field(
        None, description='d³P/dS²dσ (gamma sensitivity to vol)'
    )
    color: float | None = Field(
        None, description='d³P/dS²dt (gamma decay, PER DAY - see `dayCount`)'
    )
    ultima: float | None = Field(None, description='d³P/dσ³ (vomma sensitivity to vol)')
    dcharmDvol: float | None = Field(
        None,
        description='d³P/dSdtdσ (charm sensitivity to vol, PER DAY - see `dayCount`)',
    )
    lambda_: float | None = Field(
        None, alias='lambda', description='Leverage: delta × S / P (also called Omega)'
    )
    phi: float | None = Field(
        None,
        description='Carry-rate sensitivity. For Black-Scholes this equals rho - epsilon; exotic/numerical models may compute it independently.',
    )
    exoticInsight: ExoticInsight | None = None
    inputs: ResolvedInputs
    resolved: ResolvedSummary | None = None
    warnings: list[str] | None = Field(
        None,
        description='Non-fatal notices about this response, including ticker auto-fill, numerical-accuracy limitations or analytical fallback, and the Greek convention layer reporting a non-finite Greek that was published as 0.',
    )


class ExposureStrike(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    strike: float
    callGamma: float
    putGamma: float
    netGamma: float
    callDelta: float
    putDelta: float
    netDelta: float
    callVega: float
    putVega: float
    netVega: float
    callVanna: float
    putVanna: float
    netVanna: float
    callCharm: float
    putCharm: float
    netCharm: float
    callVomma: float
    putVomma: float
    netVomma: float


class Regime(Enum):
    positive = 'positive'
    negative = 'negative'
    neutral = 'neutral'


class ExposureSnapshot(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    spotPrice: float
    netGamma: float
    netDelta: float
    netVega: float
    netVanna: float
    netCharm: float
    netVomma: float
    callWall: float | None
    putWall: float | None
    gammaFlip: float | None
    absGamma: float | None = Field(
        None,
        description='Strike with the largest absolute net gamma in the wall/flip universe',
    )
    gammaConcentration: float | None
    regime: Regime
    topStrikes: list[ExposureStrike] = Field(
        ..., description='Top-10 strikes by absolute net gamma'
    )
    resolved: ResolvedSummary | None = None


class ExposureFullResult(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    snapshot: ExposureSnapshot
    byStrike: list[ExposureStrike]
    resolved: ResolvedSummary | None = None


class ExposureResponse(RootModel[ExposureFullResult | ExposureSnapshot]):
    root: ExposureFullResult | ExposureSnapshot = Field(
        ...,
        description='Default: ExposureFullResult ({ snapshot, byStrike }). With ?detail=snapshot: ExposureSnapshot directly.',
    )


class ScenarioMatrixEntry(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    spotChange: float = Field(
        ..., description='Relative spot perturbation, e.g. -0.05 for -5%.'
    )
    volChange: float = Field(
        ..., description='Relative volatility perturbation, e.g. 0.10 for +10%.'
    )
    spot: float = Field(
        ..., description='Scenario spot price after applying spotChange.'
    )
    volatility: float = Field(
        ..., description='Scenario volatility after applying volChange.'
    )
    price: float = Field(..., description='Option price under this scenario.')
    pnl: float = Field(..., description='Dollar P/L versus the base option price.')
    pnlPercent: float = Field(
        ..., description='Percent P/L versus the base option price.'
    )


class Model10(Enum):
    bs = 'bs'
    binomial = 'binomial'


class ScenarioResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    model: Model10 = Field(
        ...,
        description='Model used for the matrix. `bs` (European Black-Scholes) unless `model: "binomial"` was requested.',
    )
    spotChanges: list[float]
    volChanges: list[float]
    matrix: list[list[ScenarioMatrixEntry]] = Field(
        ...,
        description='2D matrix of structured cells indexed by [spotChange][volChange].',
    )
    resolved: ResolvedSummary | None = None


class Model11(Enum):
    bs = 'bs'
    heston = 'heston'
    binomial = 'binomial'


class HestonModelGreeks(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    dV0: float = Field(
        ..., description='d(price) / d(V0) — sensitivity to instantaneous variance.'
    )
    dKappa: float = Field(
        ..., description='d(price) / d(kappa) — mean-reversion speed.'
    )
    dTheta: float = Field(..., description='d(price) / d(theta) — long-run variance.')
    dVolOfVol: float = Field(..., description='d(price) / d(xi) — vol-of-vol.')
    dRho: float = Field(..., description='d(price) / d(rho) — spot/vol correlation.')


class Model12(Enum):
    bs = 'bs'
    binomial = 'binomial'


class StrategyLeg(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    type: Type
    side: Side
    quantity: float
    strike: float | None = None
    model: Model12 | None = None
    premium: float | None = Field(
        None,
        description='Per-share option premium used — supplied by the caller or computed by the model.',
    )
    costBasis: float | None = Field(
        None,
        description='Per-share cost basis for a stock leg (defaults to the shared spot).',
    )
    greeks: dict[str, float] = Field(
        ...,
        description='Per-contract Greeks for option legs; `{ delta: 1 }` for stock.',
    )


class StrategyProfitZone(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    type: str = Field(
        ...,
        description='One of: above, below, between, outside, always_profit, always_loss, complex, unknown.',
    )
    breakevens: list[float]
    profitIntervals: list[list[float | None]] | None = Field(
        None,
        description='Profitable price bands [lo, hi] for disjoint (complex) zones. A null endpoint means unbounded on that side (0 low / +inf high).',
    )


class StrategyPayoffPoint(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    price: float
    payoff: float = Field(
        ...,
        description='Total P&L at expiry at this price (intrinsic payoff plus the initial cost).',
    )
    payoffAtExpiry: float | None = None


class Unbounded(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    maxProfit: bool
    maxLoss: bool


class StrategyResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    legs: list[StrategyLeg]
    initialCost: float = Field(
        ...,
        description='Net cash flow to establish the position: negative = net debit paid, positive = net credit received. Options are x100/contract; stock is x shares.',
    )
    netGreeks: dict[str, float] = Field(
        ...,
        description='Position-level (share-equivalent) net Greeks: an option leg contributes signedQty x 100 x per-contract Greek; a stock leg contributes signedQty to delta. Short legs are negative. Excludes `lambda` (leverage is a ratio, not additive) — see each leg`s `greeks` for its lambda.',
    )
    maxProfit: float | None = Field(
        None,
        description='Maximum profit, or null when unbounded (see `unbounded.maxProfit`).',
    )
    maxLoss: float | None = Field(
        None, description='Maximum loss (most negative P&L), or null when unbounded.'
    )
    unbounded: Unbounded
    breakevens: list[float]
    profitZone: StrategyProfitZone
    riskRewardRatio: float | None = Field(
        None, description='maxProfit / |maxLoss|; null when maxLoss is 0 or unbounded.'
    )
    probabilityOfProfit: float | None = Field(
        None,
        description='Lognormal probability of finishing in a profit zone; null unless sigma and tenor are known.',
    )
    payoffCurve: list[StrategyPayoffPoint]
    resolved: ResolvedSummary | None = None


class PainByStrikeItem(BaseModel):
    strike: float | None = None
    totalPain: float | None = None


class MaxPainResponse(BaseModel):
    maxPainStrike: float | None = None
    totalPainAtMaxPain: float | None = None
    painByStrike: list[PainByStrikeItem] | None = None


class Method(Enum):
    market_straddle = 'market-straddle'
    bs_straddle = 'bs-straddle'


class ExpectedMoveResponse(BaseModel):
    spotPrice: float | None = None
    strikePrice: float | None = None
    atmIV: float | None = None
    daysToExpiry: float | None = None
    method: Method | None = None
    straddle: float | None = None
    expectedMoveAbsolute: float | None = None
    expectedMovePercent: float | None = None
    upperBound: float | None = None
    lowerBound: float | None = None
    ivApproxMove: float | None = None
    resolved: ResolvedSummary | None = None


class PdfItem(BaseModel):
    strike: float | None = None
    density: float | None = None


class CdfItem(BaseModel):
    strike: float | None = None
    cumulative: float | None = None


class Stats(BaseModel):
    impliedMove: float | None = None
    movePercent: float | None = None
    lower: float | None = None
    upper: float | None = None
    fairValue: float | None = None
    stdDev: float | None = None


class Method1(Enum):
    essvi = 'essvi'
    finite_diff = 'finite-diff'


class Quality(Enum):
    high = 'high'
    medium = 'medium'
    low = 'low'


class RiskNeutral(BaseModel):
    pdf: list[PdfItem] | None = None
    cdf: list[CdfItem] | None = None
    stats: Stats | None = None
    method: Method1 | None = None
    methodLabel: str | None = None
    quality: Quality | None = None
    fallbackReason: str | None = None


class Stats1(BaseModel):
    move: float | None = None
    movePercent: float | None = None
    lower: float | None = None
    upper: float | None = None
    expectedValue: float | None = None


class Lognormal(BaseModel):
    pdf: list[dict[str, Any]] | None = None
    cdf: list[dict[str, Any]] | None = None
    stats: Stats1 | None = None


class ProbabilityResponse(BaseModel):
    riskNeutral: RiskNeutral | None = None
    lognormal: Lognormal | None = None
    spotPrice: float | None = None
    expiration: str | None = None
    timeToExpiry: float | None = None
    riskFreeRate: float | None = None
    dividendYield: float | None = None
    resolved: ResolvedSummary | None = None


class FitError(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    ivRmse: float = Field(
        ...,
        description='Aggregate IV RMSE across the options the fit was computed from. A calibration that does not converge returns a 422 `CALIBRATION_FAILED` rather than an `ivRmse` of 0 next to unfitted parameters.',
    )
    nOptions: int = Field(
        ...,
        description='Number of usable observations admitted by the selected calibrator. This can differ from the submitted chain count: Heston requires a supplied IV in its accepted range; SABR, variance-gamma and jump-diffusion can derive IV from a usable option price; and local-vol/eSSVI deduplicates call/put observations at the same expiry and strike.',
    )


class BucketRmse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    atm: float | None = Field(..., description='|moneyness − 1| < 0.05.')
    otm_call: float | None = Field(..., description='moneyness > 1.05.')
    otm_put: float | None = Field(..., description='moneyness < 0.95.')
    deep_otm: float | None = Field(..., description='|moneyness − 1| > 0.20.')


class BucketCount(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    atm: int
    otm_call: int
    otm_put: int
    deep_otm: int


class Type2(Enum):
    call = 'call'
    put = 'put'


class FitResidual(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    strike: float
    type: Type2
    moneyness: float = Field(..., description='K / S at the time of calibration.')
    priceResidual: float = Field(
        ...,
        description='Model price − market mid (in price units, NOT IV units — aggregate `fitError.ivRmse` is the IV-space companion).',
    )


class RegimeResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    daily: dict[str, Any] | None = Field(
        None,
        description='Latest row from regime_daily for symbol=MARKET, scope=market, ordered by market_date desc. Null when no row exists.',
    )
    intraday: dict[str, Any] | None = Field(
        None,
        description='Latest row from regime_intraday for symbol=MARKET, scope=market, ordered by (market_date, scan_time) desc. Null when no row exists.',
    )


class MaxPainCurveRow(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    strike: float
    callPain: float
    putPain: float
    totalPain: float


class SnapshotResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    ticker: str
    date: date_aliased
    spotPrice: float | None
    maxPain: float | None
    netGex: float | None
    netDex: float | None
    atmIv: float | None
    atmIv7d: float | None
    atmIv30d: float | None
    atmIv90d: float | None
    putCallRatio: float | None
    ivSkew25d: float | None
    dividendYield: float | None
    totalVolume: float | None
    totalOi: float | None
    callVolume: float | None
    putVolume: float | None
    callOi: float | None
    putOi: float | None
    expectedMovePct: float | None
    ivRank: float | None
    ivPercentile: float | None
    hv20d: float | None
    hv60d: float | None
    maxPainCurve: list[MaxPainCurveRow] | None = Field(
        None,
        description='Max-pain curve series for the chart UI: per-strike rows of { strike, callPain, putPain, totalPain }.',
    )
    gexByStrike: list[dict[str, Any]] | None = Field(
        None, description='GEX-by-strike series; opaque payload'
    )
    dexByStrike: list[dict[str, Any]] | None = Field(
        None, description='DEX-by-strike series; opaque payload'
    )
    vannaByStrike: list[dict[str, Any]] | None = Field(
        None, description='Vanna-by-strike series; opaque payload'
    )
    charmByStrike: list[dict[str, Any]] | None = Field(
        None, description='Charm-by-strike series; opaque payload'
    )
    vommaByStrike: list[dict[str, Any]] | None = Field(
        None, description='Vomma-by-strike series; opaque payload'
    )
    volSkew: dict[str, Any] | None = Field(
        None, description='Vol-skew curve; opaque payload'
    )
    probabilityData: dict[str, Any] | None = Field(
        None, description='Risk-neutral probability data; opaque payload'
    )
    chainData: list[dict[str, Any]] | None = Field(
        None, description='Recent option chain rows; opaque payload'
    )
    analyticsExpiry: str | None
    chainExpiry: str | None


class SchemaVersion(IntEnum):
    integer_1 = 1


class DteWindow(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    minDte: float
    maxDte: float
    unit: str


class DealerRegime(Enum):
    positive = 'positive'
    negative = 'negative'
    neutral = 'neutral'


class TopContributingStrike(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    strike: float
    netGex: float
    netDex: float


class EodExposureResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    schemaVersion: SchemaVersion = Field(
        ..., description='Contract version; bumped on any breaking shape change.'
    )
    symbol: str
    date: date_aliased = Field(
        ..., description='EOD session the levels are computed from.'
    )
    asOf: AwareDatetime | None = Field(
        None, description='When the pipeline computed this row.'
    )
    source: str = Field(..., description='Provenance tag, e.g. "eod_options_snapshot".')
    dteWindow: DteWindow = Field(
        ..., description='Expiration window every level is computed over.'
    )
    spotPrice: float | None
    netGex: float | None = Field(
        None, description='Net dollar gamma exposure over the window (see units).'
    )
    netDex: float | None = Field(
        None, description='Net dollar delta exposure over the window (see units).'
    )
    gammaMagnet: float | None = Field(
        None, description='Strike with the largest absolute net gamma in the window.'
    )
    gammaFlip: float | None = Field(
        None, description='Net-gamma zero crossing (repriced).'
    )
    callWall: float | None = Field(
        None, description='Largest call-side gamma concentration (resistance).'
    )
    putWall: float | None = Field(
        None, description='Largest put-side gamma concentration (support).'
    )
    dealerRegime: DealerRegime = Field(
        ..., description='Sign of net gamma at spot over the window.'
    )
    expectedMovePct30d: float | None = Field(
        None, description='30-day ATM-implied move as a decimal fraction.'
    )
    expectedMove30d: float | None = Field(
        None,
        description='30-day expected move in dollars (spotPrice * expectedMovePct30d).',
    )
    topContributingStrikes: list[TopContributingStrike] = Field(
        ...,
        description='Strikes contributing most to net gamma, ordered by absolute gamma contribution.',
    )
    topContributingStrikesLimit: int = Field(
        ..., description='Max number of rows returned in topContributingStrikes.'
    )
    units: dict[str, str] = Field(
        ...,
        description='Plain-language units for the exposure and expected-move fields.',
    )


class MetricsResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    symbol: str
    date: date_aliased
    atmIv: float | None
    ivRank: float | None
    ivPercentile: float | None
    hv20d: float | None
    hv60d: float | None
    putCallRatio: float | None
    totalVolume: float | None
    totalOi: float | None
    callVolume: float | None
    putVolume: float | None
    callOi: float | None
    putOi: float | None
    maxPain: float | None
    expectedMovePct: float | None


class IVSurfacePoint(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    strike: float = Field(..., description='Strike price in dollars.')
    expiration: date_aliased = Field(..., description='Option expiration date.')
    yte: float = Field(
        ..., description='Years to expiration as a decimal (calendar-day fraction).'
    )
    iv: float | None = Field(
        None,
        description='Unified IV — smv → callIV → putIV fallback. Null only if all three sources are missing.',
    )
    callIV: float | None = Field(None, description='Call-side mid IV.')
    putIV: float | None = Field(None, description='Put-side mid IV.')
    smv: float | None = Field(
        None, description='Smoothed surface IV (warehouse-derived).'
    )


class ListResponse(BaseModel):
    count: float | None = None
    data: list[dict[str, Any]] | None = None


class MetricsBatchResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    count: float
    data: list[MetricsResponse]


class HistoryRow(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    market_date: date_aliased | None = None
    spot_price: float | None = None
    call_volume: float | None = None
    put_volume: float | None = None
    call_oi: float | None = None
    put_oi: float | None = None
    put_call_ratio: float | None = None
    atm_iv: float | None = Field(
        None, description='Generic ATM IV (all expirations blended).'
    )
    atm_iv_7d: float | None = Field(
        None,
        description='7-day tenor ATM IV — closest persisted proxy to event-week vol around earnings.',
    )
    atm_iv_30d: float | None = None
    volume_oi_ratio: float | None = None


class HistoryResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    symbol: str | None = None
    count: float | None = None
    data: list[HistoryRow] | None = None


class WorkerPool(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    size: conint(ge=0)
    ready: conint(ge=0)
    busy: conint(ge=0)
    queued: conint(ge=0)
    degraded: bool


class Redis(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    configured: bool
    connected: bool
    state: str | None
    consecutiveCommandFailures: conint(ge=0)
    lastCommandFailureAt: AwareDatetime | None


class Rejections(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    byStatus: dict[str, conint(ge=0)] = Field(..., max_length=3)
    byBucket: dict[str, conint(ge=0)] = Field(..., max_length=500)
    total: conint(ge=0)
    overflowed: bool
    lastAt: conint(ge=0) | None


class HealthResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    status: str = Field(..., examples=['ok'])
    service: str = Field(..., examples=['data-api'])
    version: str = Field(..., examples=['v1'])
    uptime: float = Field(..., examples=[12345.67])
    timestamp: AwareDatetime
    workerPool: WorkerPool | None = Field(
        None,
        description='Current compute-worker capacity. Null means heavy computations have no worker pool and may use their documented fallback path.',
    )
    redis: Redis = Field(
        ...,
        description='Redis connectivity. When Redis is down, the rate limiter and concurrency caps fall back to per-process memory and stop being global across replicas; response caching is bypassed.',
    )
    rejections: Rejections = Field(
        ...,
        description='Per-process refusal counters since startup. The path breakdown is capped; overflowed=true means totals remain complete but byBucket is partial.',
    )


class Issue(BaseModel):
    path: list[Any] | None = None
    message: str | None = None
    code: str | None = None


class ValidationError(BaseModel):
    error: str = Field(..., examples=['Validation failed'])
    issues: list[Issue] | None = None


class AuthError(BaseModel):
    error: str = Field(..., examples=['API key required'])
    message: str | None = Field(
        None,
        examples=[
            'Provide an API key via Authorization: Bearer oas_live_... or X-API-Key header'
        ],
    )


class RequiredScope(Enum):
    compute = 'compute'
    data = 'data'
    streaming = 'streaming'


class ScopeError(BaseModel):
    error: str = Field(..., examples=['Insufficient API key scope'])
    requiredScope: RequiredScope | None = None


class RateLimitError(BaseModel):
    error: str = Field(..., examples=['Rate limit exceeded'])
    limit: float = Field(..., examples=[120])
    retryAfter: float | None = Field(
        None, description='Seconds until rate limit resets', examples=[42]
    )


class ComputeConcurrencyLimitError(BaseModel):
    error: str = Field(..., examples=['Too many concurrent compute requests'])
    code: str = Field(..., examples=['COMPUTE_CONCURRENCY_LIMIT'])
    message: str = Field(
        ..., examples=['Too many concurrent expensive compute requests']
    )
    current: float = Field(..., examples=[2])
    max: float = Field(..., examples=[2])


class Scope(Enum):
    day = 'day'


class CalibrationQuotaError(BaseModel):
    error: str = Field(..., examples=['Daily calibration quota exceeded'])
    code: str = Field(..., examples=['CALIBRATION_QUOTA_EXCEEDED'])
    scope: Scope = Field(..., description='Which quota window was exceeded')
    limit: float = Field(..., description='Hard cap for the scope (500 per day)')
    used: float = Field(
        ...,
        description='Number of successful calibrations the user has made in the scope window',
    )
    resetsAt: AwareDatetime = Field(
        ..., description='ISO 8601 timestamp when the quota window resets (UTC)'
    )


class SemanticValidationError(BaseModel):
    error: str = Field(..., examples=['Invalid Heston parameters'])
    code: str | None = Field(None, examples=['INVALID_HESTON_PARAMS'])
    message: str | None = Field(
        None,
        examples=['Heston sensitivity requires v0, kappa, theta, xi/volOfVol, and rho'],
    )
    details: list[str] | None = None
    missingFields: list[str] | None = Field(
        None,
        description='Fields that ticker resolution could not fill, present on RESOLUTION_FAILED responses',
        examples=[['S', 'sigma']],
    )
    warnings: list[str] | None = Field(
        None,
        description='Non-fatal resolver warnings, present when ticker auto-fill ran',
    )
    partialResolved: dict[str, Any] | None = Field(
        None,
        description='Resolved market inputs available before the semantic validation failure',
    )


class MethodNotAllowedError(BaseModel):
    error: str = Field(..., examples=['Method Not Allowed'])
    code: str = Field(..., examples=['METHOD_NOT_ALLOWED'])
    message: str = Field(..., examples=['Use POST for compute endpoints.'])
    allowedMethods: list[str] = Field(..., examples=[['POST']])
    docs: AnyUrl | None = Field(
        None, examples=['https://data.optionsanalysissuite.com/docs']
    )


class NotFoundError(BaseModel):
    error: str = Field(..., examples=['No data found for this symbol'])


class InternalError(BaseModel):
    error: str = Field(..., examples=['Internal server error'])


class ServiceUnavailableError(BaseModel):
    error: str = Field(..., examples=['Worker pool draining; service unavailable'])
    code: str | None = Field(None, examples=['WORKER_POOL_UNAVAILABLE'])


class PriceResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    price: float = Field(..., description='Theoretical option price')
    model: str = Field(
        ..., description='Pricing model name (e.g. "Black-Scholes-Merton")'
    )
    inputs: ResolvedInputs
    greeks: dict[str, float] | None = Field(
        None,
        description='Per-Greek values produced as a side effect of pricing for some models. Binomial returns delta/gamma. The default numerical PDE path returns delta/gamma/theta; an enhanced-control PDE request may return only price. Vega and rho are absent from numerical PDE pricing because that solve does not measure them. An analytical PDE fallback can return vega/rho and is identified in `warnings`. Use /v1/compute/greeks for the full 17-Greek response across all models.',
    )
    mcStats: McStats | None = None
    distribution: McDistribution | None = None
    fullPaths: list[list[float]] | None = Field(
        None,
        description='Raw simulated paths. Present only when `model: "mc"` and `detail: "full"`. Subsampled uniformly to satisfy two server-enforced caps: a max path count (default 1,000,000) and a max total numbers serialized (default 5,000,000). `fullPathsTruncated: true` flags when subsampling ran.',
    )
    fullPathsTruncated: bool | None = Field(
        None,
        description='True when the response was uniformly subsampled because the simulated path count exceeded the cap.',
    )
    resolved: ResolvedSummary | None = None
    warnings: list[str] | None = Field(
        None,
        description='Non-fatal notices, including ticker-resolution warnings and disclosure that a requested numerical model used an analytical fallback.',
    )


class SensitivityPoint(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    x: float = Field(..., description='Sweep variable value at this point.')
    price: float | None = None
    delta: float | None = None
    gamma: float | None = None
    vega: float | None = None
    theta: float | None = None
    rho: float | None = None
    epsilon: float | None = None
    vanna: float | None = None
    charm: float | None = None
    vomma: float | None = None
    veta: float | None = None
    speed: float | None = None
    zomma: float | None = None
    color: float | None = None
    ultima: float | None = None
    lambda_: float | None = Field(None, alias='lambda')
    phi: float | None = None
    dcharmDvol: float | None = None
    modelGreeks: HestonModelGreeks | None = None


class FitDiagnostics(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    residuals: list[FitResidual] = Field(
        ...,
        description='Per-option residuals (model price − market mid). Capped at 100, sorted by descending |residual| so the worst fits survive the cap.',
    )
    bucketRmse: BucketRmse = Field(
        ...,
        description='RMSE of price residuals within each moneyness bucket. Null when the bucket has no eligible options.',
    )
    bucketCount: BucketCount = Field(
        ...,
        description='Number of options included in each moneyness bucket, mirrors `bucketRmse`.',
    )
    worstFitOption: FitResidual | None = Field(
        None,
        description='Single worst-fitting option in absolute residual terms. Null if no options were re-priceable.',
    )


class IVSurfaceResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    ticker: str = Field(
        ..., description='Underlying symbol echoed from the request (uppercased).'
    )
    date: date_aliased = Field(
        ..., description='Market date the surface snapshot applies to.'
    )
    spotPrice: float = Field(
        ..., description='Spot price observed for this surface, in dollars.'
    )
    expirations: list[date_aliased] = Field(
        ..., description='Sorted list of distinct expiration dates present in `data`.'
    )
    rowCount: int = Field(
        ..., description='Number of strike × expiration rows returned.'
    )
    data: list[IVSurfacePoint]


class SensitivityResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    axis: Axis
    model: Model11 = Field(..., description='Model used for the sweep.')
    data: list[SensitivityPoint]
    resolved: ResolvedSummary | None = None


class CalibrateResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    model: str
    symbol: str
    expiration: str
    params: dict[str, float | str]
    fitError: FitError
    fitDiagnostics: FitDiagnostics | None = None
    calibrationTimeMs: float
    calibrationId: str
    provider: str
