# generated by datamodel-codegen:
#   filename:  tmpxx6f3tei.json
#   timestamp: 2026-05-04T06:51:02+00:00

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum
from typing import Any, Literal

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    PositiveFloat,
    RootModel,
    confloat,
    conint,
    constr,
)


class Model(Enum):
    bs = 'bs'
    heston = 'heston'
    sabr = 'sabr'
    jd = 'jd'
    vg = 'vg'
    binomial = 'binomial'
    pde = 'pde'
    fft = 'fft'
    mc = 'mc'
    localvol = 'localvol'
    barrier = 'barrier'
    asian = 'asian'
    lookback = 'lookback'
    digital = 'digital'
    compound = 'compound'
    chooser = 'chooser'
    multiasset = 'multiasset'


class SigmaSource(Enum):
    auto = 'auto'
    atmIv = 'atmIv'
    hv = 'hv'


class RateMode(Enum):
    matched = 'matched'
    fixedTenor = 'fixedTenor'


class RateTenor(Enum):
    field_1MO = '1MO'
    field_3MO = '3MO'
    field_6MO = '6MO'
    field_1Y = '1Y'
    field_2Y = '2Y'
    field_5Y = '5Y'
    field_10Y = '10Y'
    field_30Y = '30Y'


class SpotSource(Enum):
    snapshot = 'snapshot'


class Resolve(BaseModel):
    spot: bool | None = True
    sigma: bool | None = True
    sigmaSource: SigmaSource | None = 'auto'
    dividend: bool | None = True
    rate: bool | None = True
    rateMode: RateMode | None = 'matched'
    rateTenor: RateTenor | None = None
    tenor: bool | None = True
    spotSource: SpotSource | None = 'snapshot'
    calibration: bool | None = False


class Detail(Enum):
    summary = 'summary'
    distribution = 'distribution'
    full = 'full'


class Resolve1(BaseModel):
    spot: bool | None = True
    sigma: bool | None = True
    sigmaSource: SigmaSource | None = 'auto'
    dividend: bool | None = True
    rate: bool | None = True
    rateMode: RateMode | None = 'matched'
    rateTenor: RateTenor | None = None
    tenor: bool | None = True
    spotSource: SpotSource | None = 'snapshot'
    calibration: bool | None = False


class Resolve2(BaseModel):
    spot: bool | None = True
    sigma: bool | None = True
    sigmaSource: SigmaSource | None = 'auto'
    dividend: bool | None = True
    rate: bool | None = True
    rateMode: RateMode | None = 'matched'
    rateTenor: RateTenor | None = None
    tenor: bool | None = True
    spotSource: SpotSource | None = 'snapshot'
    calibration: bool | None = False


class Resolve3(BaseModel):
    spot: bool | None = True
    sigma: bool | None = True
    sigmaSource: SigmaSource | None = 'auto'
    dividend: bool | None = True
    rate: bool | None = True
    rateMode: RateMode | None = 'matched'
    rateTenor: RateTenor | None = None
    tenor: bool | None = True
    spotSource: SpotSource | None = 'snapshot'
    calibration: bool | None = False


class Resolve4(BaseModel):
    spot: bool | None = True
    sigma: bool | None = True
    sigmaSource: SigmaSource | None = 'auto'
    dividend: bool | None = True
    rate: bool | None = True
    rateMode: RateMode | None = 'matched'
    rateTenor: RateTenor | None = None
    tenor: bool | None = True
    spotSource: SpotSource | None = 'snapshot'
    calibration: bool | None = False


class Resolve5(BaseModel):
    spot: bool | None = True
    sigma: bool | None = True
    sigmaSource: SigmaSource | None = 'auto'
    dividend: bool | None = True
    rate: bool | None = True
    rateMode: RateMode | None = 'matched'
    rateTenor: RateTenor | None = None
    tenor: bool | None = True
    spotSource: SpotSource | None = 'snapshot'
    calibration: bool | None = False


class Strike(BaseModel):
    strike_cents: float
    stk_px_cents: float
    c_oi: float
    p_oi: float
    gamma: float
    delta: float | None = None
    vega: float | None = None
    smooth_smv_vol: float | None = None
    c_mid_iv: float | None = None
    p_mid_iv: float | None = None
    yte: float | None = None
    expir_date: str | None = None


class ExposureRequest(BaseModel):
    strikes: list[Strike] = Field(..., max_length=5000, min_length=1)
    spotPrice: PositiveFloat
    riskFreeRate: float | None = 0.05
    dividendYield: float | None = 0
    wallMaxDte: float | None = None


class ScenarioRequest(BaseModel):
    isCall: bool
    S: PositiveFloat
    K: PositiveFloat
    r: float
    q: float | None = 0
    sigma: confloat(ge=0.0)
    t: confloat(ge=0.0)
    spotChanges: list[float] = Field(..., max_length=20, min_length=2)
    volChanges: list[float] = Field(..., max_length=20, min_length=2)


class Axis(Enum):
    spot = 'spot'
    time = 'time'
    volatility = 'volatility'


class Model6(Enum):
    bs = 'bs'
    heston = 'heston'


class Strike1(BaseModel):
    strike: PositiveFloat
    callOI: confloat(ge=0.0)
    putOI: confloat(ge=0.0)


class MaxPainRequest(BaseModel):
    strikes: list[Strike1] = Field(..., max_length=5000, min_length=1)


class ExpectedMoveRequest1(BaseModel):
    spotPrice: PositiveFloat
    strikePrice: PositiveFloat | None = None
    riskFreeRate: float | None = 0.05
    dividendYield: float | None = 0
    atmIV: PositiveFloat
    daysToExpiry: PositiveFloat
    atmCallPrice: confloat(ge=0.0) | None = None
    atmPutPrice: confloat(ge=0.0) | None = None
    atmIv: PositiveFloat | None = Field(
        None,
        description='Alias for `atmIV`. Accepted so callers can pipe the `atmIv` field from /v1/data/metrics/{symbol} or /v1/data/snapshot/{symbol} directly.',
    )


class ExpectedMoveRequest2(BaseModel):
    spotPrice: PositiveFloat
    strikePrice: PositiveFloat | None = None
    riskFreeRate: float | None = 0.05
    dividendYield: float | None = 0
    atmIV: PositiveFloat | None = None
    daysToExpiry: PositiveFloat
    atmCallPrice: confloat(ge=0.0) | None = None
    atmPutPrice: confloat(ge=0.0) | None = None
    atmIv: PositiveFloat = Field(
        ...,
        description='Alias for `atmIV`. Accepted so callers can pipe the `atmIv` field from /v1/data/metrics/{symbol} or /v1/data/snapshot/{symbol} directly.',
    )


class ExpectedMoveRequest(RootModel[ExpectedMoveRequest1 | ExpectedMoveRequest2]):
    root: ExpectedMoveRequest1 | ExpectedMoveRequest2


class Strike2(RootModel[PositiveFloat]):
    root: PositiveFloat


class Iv(RootModel[confloat(ge=0.0)]):
    root: confloat(ge=0.0)


class ProbabilityRequest1(BaseModel):
    mode: Literal['simple'] = 'simple'
    spotPrice: PositiveFloat
    strikes: list[Strike2] = Field(..., max_length=500, min_length=3)
    ivs: list[Iv] = Field(..., max_length=500, min_length=3)
    riskFreeRate: float | None = 0.05
    dividendYield: float | None = 0
    timeToExpiry: PositiveFloat


class ProbabilityRequest2(BaseModel):
    mode: Literal['full']
    symbol: constr(min_length=1, max_length=10)
    expiration: str | None = None
    riskFreeRate: float | None = 0.05
    dividendYield: float | None = 0


class ProbabilityRequest(RootModel[ProbabilityRequest1 | ProbabilityRequest2]):
    root: ProbabilityRequest1 | ProbabilityRequest2


class Model7(Enum):
    heston = 'heston'
    sabr = 'sabr'
    vg = 'vg'
    jd = 'jd'
    localvol = 'localvol'


class CalibrateRequest(BaseModel):
    model: Model7 = Field(..., description='Model to calibrate')
    symbol: str = Field(..., description='Ticker symbol (e.g. "SPY")')
    expiration: str | None = Field(
        None,
        description='Optional: specific expiration date (YYYY-MM-DD). Defaults to nearest.',
    )
    modelParams: dict[str, Any] | None = Field(
        None,
        description='Model-specific calibration options. Supported keys by model:\n\n**heston:** `accuracyMode` ("fast" | "balanced" | "precise", default "balanced")\n\n**sabr:** `fixBeta` (boolean, default true), `accuracyMode` ("fast" | "balanced" | "precise")\n\n**jd:** `modelType` / `jdModel` ("kou" | "merton" | "bates", default "kou")\n\n**vg / localvol:** no extra options',
    )


class ResolvedInputs(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    isCall: bool
    S: float = Field(..., description='Spot price')
    K: float = Field(..., description='Strike price')
    r: float = Field(..., description='Risk-free rate (decimal)')
    q: float = Field(..., description='Dividend yield (decimal)')
    sigma: float = Field(..., description='Volatility (decimal)')
    t: float = Field(..., description='Time to expiry (years)')
    modelParams: dict[str, Any] | None = Field(
        None, description='Model-specific knobs supplied or filled in by calibration'
    )
    calibrationId: str | None = Field(
        None,
        description='30-second in-memory handle returned by /v1/compute/calibrate. Persist `modelParams` for durable reuse.',
    )


class ResolvedSummary1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    value: float
    source: str


class ResolvedSummary(RootModel[dict[str, ResolvedSummary1]]):
    root: dict[str, ResolvedSummary1]


class McStats(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    stdError: float = Field(..., description='Standard error of the price estimate.')
    ciLow: float = Field(
        ..., description='Lower bound of the 95% confidence interval for the price.'
    )
    ciHigh: float = Field(
        ..., description='Upper bound of the 95% confidence interval for the price.'
    )
    nPaths: int = Field(
        ...,
        description='Effective number of paths the estimate was built from. With antithetic variates enabled this is up to 2× the requested `nPaths`.',
    )


class Percentiles(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    p1: float
    p5: float
    p10: float
    p25: float
    p50: float = Field(..., description='Median.')
    p75: float
    p90: float
    p95: float
    p99: float


class Histogram(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    binEdges: list[float]
    counts: list[int]


class McDistribution(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    count: int = Field(
        ..., description='Number of simulated paths the distribution was built from.'
    )
    mean: float = Field(..., description='Mean of the simulated terminal price.')
    min: float = Field(..., description='Minimum simulated terminal price.')
    max: float = Field(..., description='Maximum simulated terminal price.')
    percentiles: Percentiles = Field(
        ...,
        description='Linearly-interpolated percentiles of the simulated terminal price.',
    )
    histogram: Histogram = Field(
        ...,
        description='Equal-width histogram. `binEdges` length is `counts.length + 1`; bin `i` covers `[binEdges[i], binEdges[i+1])`. Bin count is configurable up to a server-enforced cap of 200; default 50.',
    )


class ExoticInsightMetric(BaseModel):
    label: str
    value: str
    rawValue: float
    highlight: bool | None = None


class VerdictType(Enum):
    positive = 'positive'
    negative = 'negative'
    neutral = 'neutral'


class ExoticInsight(BaseModel):
    model: str
    title: str
    subtitle: str
    accentColor: str
    metrics: list[ExoticInsightMetric]
    verdict: str
    verdictType: VerdictType


class GreeksResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    model: str
    price: float
    delta: float | None = Field(None, description='dP/dS')
    vega: float | None = Field(None, description='dP/dσ (per 1% vol change)')
    theta: float | None = Field(None, description='dP/dt (per day)')
    rho: float | None = Field(None, description='dP/dr (per 1% rate change)')
    epsilon: float | None = Field(
        None, description='dP/dq (per 1% dividend yield change)'
    )
    gamma: float | None = Field(None, description='d²P/dS²')
    vanna: float | None = Field(None, description='d²P/dSdσ')
    charm: float | None = Field(None, description='d²P/dSdt (delta decay)')
    vomma: float | None = Field(None, description='d²P/dσ² (vega convexity)')
    veta: float | None = Field(None, description='d²P/dσdt (vega decay)')
    speed: float | None = Field(None, description='d³P/dS³ (gamma sensitivity to spot)')
    zomma: float | None = Field(
        None, description='d³P/dS²dσ (gamma sensitivity to vol)'
    )
    color: float | None = Field(None, description='d³P/dS²dt (gamma decay)')
    ultima: float | None = Field(None, description='d³P/dσ³ (vomma sensitivity to vol)')
    dcharmDvol: float | None = Field(
        None, description='d³P/dSdtdσ (charm sensitivity to vol)'
    )
    lambda_: float | None = Field(
        None, alias='lambda', description='Leverage: delta × S / P (also called Omega)'
    )
    phi: float | None = Field(
        None, description='d/d(r−q) = rho − epsilon (carry sensitivity)'
    )
    exoticInsight: ExoticInsight | None = None
    inputs: ResolvedInputs
    resolved: ResolvedSummary | None = None
    warnings: list[str] | None = Field(
        None, description='Resolution warnings emitted during ticker auto-fill'
    )


class ExposureStrike(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    strike: float
    callGamma: float
    putGamma: float
    netGamma: float
    callDelta: float
    putDelta: float
    netDelta: float
    callVega: float
    putVega: float
    netVega: float
    callVanna: float
    putVanna: float
    netVanna: float
    callCharm: float
    putCharm: float
    netCharm: float
    callVomma: float
    putVomma: float
    netVomma: float


class Regime(Enum):
    positive = 'positive'
    negative = 'negative'
    neutral = 'neutral'


class ExposureSnapshot(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    spotPrice: float
    netGamma: float
    netDelta: float
    netVega: float
    netVanna: float
    netCharm: float
    netVomma: float
    callWall: float | None
    putWall: float | None
    gammaFlip: float | None
    absGamma: float | None = Field(
        None,
        description='Strike with the largest absolute net gamma in the wall/flip universe',
    )
    gammaConcentration: float | None
    regime: Regime
    topStrikes: list[ExposureStrike] = Field(
        ..., description='Top-10 strikes by absolute net gamma'
    )


class ExposureFullResult(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    snapshot: ExposureSnapshot
    byStrike: list[ExposureStrike]


class ExposureResponse(RootModel[ExposureFullResult | ExposureSnapshot]):
    root: ExposureFullResult | ExposureSnapshot = Field(
        ...,
        description='Default: ExposureFullResult ({ snapshot, byStrike }). With ?detail=snapshot: ExposureSnapshot directly.',
    )


class ScenarioMatrixEntry(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    spotChange: float = Field(
        ..., description='Relative spot perturbation, e.g. -0.05 for -5%.'
    )
    volChange: float = Field(
        ..., description='Relative volatility perturbation, e.g. 0.10 for +10%.'
    )
    spot: float = Field(
        ..., description='Scenario spot price after applying spotChange.'
    )
    volatility: float = Field(
        ..., description='Scenario volatility after applying volChange.'
    )
    price: float = Field(..., description='Option price under this scenario.')
    pnl: float = Field(..., description='Dollar P/L versus the base option price.')
    pnlPercent: float = Field(
        ..., description='Percent P/L versus the base option price.'
    )


class ScenarioResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    spotChanges: list[float]
    volChanges: list[float]
    matrix: list[list[ScenarioMatrixEntry]] = Field(
        ...,
        description='2D matrix of structured cells indexed by [spotChange][volChange].',
    )


class Model8(Enum):
    bs = 'bs'
    heston = 'heston'


class HestonModelGreeks(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    dV0: float = Field(
        ..., description='d(price) / d(V0) — sensitivity to instantaneous variance.'
    )
    dKappa: float = Field(
        ..., description='d(price) / d(kappa) — mean-reversion speed.'
    )
    dTheta: float = Field(..., description='d(price) / d(theta) — long-run variance.')
    dVolOfVol: float = Field(..., description='d(price) / d(xi) — vol-of-vol.')
    dRho: float = Field(..., description='d(price) / d(rho) — spot/vol correlation.')


class PainByStrikeItem(BaseModel):
    strike: float | None = None
    totalPain: float | None = None


class MaxPainResponse(BaseModel):
    maxPainStrike: float | None = None
    totalPainAtMaxPain: float | None = None
    painByStrike: list[PainByStrikeItem] | None = None


class Method(Enum):
    market_straddle = 'market-straddle'
    bs_straddle = 'bs-straddle'


class ExpectedMoveResponse(BaseModel):
    spotPrice: float | None = None
    strikePrice: float | None = None
    atmIV: float | None = None
    daysToExpiry: float | None = None
    method: Method | None = None
    straddle: float | None = None
    expectedMoveAbsolute: float | None = None
    expectedMovePercent: float | None = None
    upperBound: float | None = None
    lowerBound: float | None = None
    ivApproxMove: float | None = None


class PdfItem(BaseModel):
    strike: float | None = None
    density: float | None = None


class CdfItem(BaseModel):
    strike: float | None = None
    cumulative: float | None = None


class Stats(BaseModel):
    impliedMove: float | None = None
    movePercent: float | None = None
    lower: float | None = None
    upper: float | None = None
    fairValue: float | None = None
    stdDev: float | None = None


class Method1(Enum):
    essvi = 'essvi'
    finite_diff = 'finite-diff'


class Quality(Enum):
    high = 'high'
    medium = 'medium'
    low = 'low'


class RiskNeutral(BaseModel):
    pdf: list[PdfItem] | None = None
    cdf: list[CdfItem] | None = None
    stats: Stats | None = None
    method: Method1 | None = None
    methodLabel: str | None = None
    quality: Quality | None = None
    fallbackReason: str | None = None


class Stats1(BaseModel):
    move: float | None = None
    movePercent: float | None = None
    lower: float | None = None
    upper: float | None = None
    expectedValue: float | None = None


class Lognormal(BaseModel):
    pdf: list[dict[str, Any]] | None = None
    cdf: list[dict[str, Any]] | None = None
    stats: Stats1 | None = None


class ProbabilityResponse(BaseModel):
    riskNeutral: RiskNeutral | None = None
    lognormal: Lognormal | None = None
    spotPrice: float | None = None
    expiration: str | None = None
    timeToExpiry: float | None = None
    riskFreeRate: float | None = None
    dividendYield: float | None = None


class FitError(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    ivRmse: float = Field(
        ..., description='Aggregate IV RMSE across all options used for the fit.'
    )
    nOptions: int = Field(..., description='Number of options included in the fit.')


class BucketRmse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    atm: float | None = Field(..., description='|moneyness − 1| < 0.05.')
    otm_call: float | None = Field(..., description='moneyness > 1.05.')
    otm_put: float | None = Field(..., description='moneyness < 0.95.')
    deep_otm: float | None = Field(..., description='|moneyness − 1| > 0.20.')


class BucketCount(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    atm: int
    otm_call: int
    otm_put: int
    deep_otm: int


class Type(Enum):
    call = 'call'
    put = 'put'


class FitResidual(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    strike: float
    type: Type
    moneyness: float = Field(..., description='K / S at the time of calibration.')
    priceResidual: float = Field(
        ...,
        description='Model price − market mid (in price units, NOT IV units — aggregate `fitError.ivRmse` is the IV-space companion).',
    )


class RegimeResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    daily: dict[str, Any] | None = Field(
        None,
        description='Latest row from regime_daily for symbol=MARKET, scope=market, ordered by market_date desc. Null when no row exists.',
    )
    intraday: dict[str, Any] | None = Field(
        None,
        description='Latest row from regime_intraday for symbol=MARKET, scope=market, ordered by (market_date, scan_time) desc. Null when no row exists.',
    )


class MaxPainCurveRow(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    strike: float
    callPain: float
    putPain: float
    totalPain: float


class SnapshotResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    ticker: str
    date: date_aliased
    spotPrice: float | None
    maxPain: float | None
    netGex: float | None
    netDex: float | None
    atmIv: float | None
    atmIv7d: float | None
    atmIv30d: float | None
    atmIv90d: float | None
    putCallRatio: float | None
    ivSkew25d: float | None
    dividendYield: float | None
    totalVolume: float | None
    totalOi: float | None
    callVolume: float | None
    putVolume: float | None
    callOi: float | None
    putOi: float | None
    expectedMovePct: float | None
    ivRank: float | None
    ivPercentile: float | None
    hv20d: float | None
    hv60d: float | None
    maxPainCurve: list[MaxPainCurveRow] | None = Field(
        None,
        description='Max-pain curve series for the chart UI: per-strike rows of { strike, callPain, putPain, totalPain }.',
    )
    gexByStrike: list[dict[str, Any]] | None = Field(
        None, description='GEX-by-strike series; opaque payload'
    )
    dexByStrike: list[dict[str, Any]] | None = Field(
        None, description='DEX-by-strike series; opaque payload'
    )
    vannaByStrike: list[dict[str, Any]] | None = Field(
        None, description='Vanna-by-strike series; opaque payload'
    )
    charmByStrike: list[dict[str, Any]] | None = Field(
        None, description='Charm-by-strike series; opaque payload'
    )
    vommaByStrike: list[dict[str, Any]] | None = Field(
        None, description='Vomma-by-strike series; opaque payload'
    )
    volSkew: dict[str, Any] | None = Field(
        None, description='Vol-skew curve; opaque payload'
    )
    probabilityData: dict[str, Any] | None = Field(
        None, description='Risk-neutral probability data; opaque payload'
    )
    chainData: list[dict[str, Any]] | None = Field(
        None, description='Recent option chain rows; opaque payload'
    )
    analyticsExpiry: str | None
    chainExpiry: str | None


class MetricsResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    symbol: str
    date: date_aliased
    atmIv: float | None
    ivRank: float | None
    ivPercentile: float | None
    hv20d: float | None
    hv60d: float | None
    putCallRatio: float | None
    totalVolume: float | None
    totalOi: float | None
    callVolume: float | None
    putVolume: float | None
    callOi: float | None
    putOi: float | None
    maxPain: float | None
    expectedMovePct: float | None


class IVSurfacePoint(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    strike: float = Field(..., description='Strike price in dollars.')
    expiration: date_aliased = Field(..., description='Option expiration date.')
    yte: float = Field(
        ..., description='Years to expiration as a decimal (calendar-day fraction).'
    )
    iv: float | None = Field(
        None,
        description='Unified IV — smv → callIV → putIV fallback. Null only if all three sources are missing.',
    )
    callIV: float | None = Field(None, description='Call-side mid IV.')
    putIV: float | None = Field(None, description='Put-side mid IV.')
    smv: float | None = Field(
        None, description='Smoothed surface IV (warehouse-derived).'
    )


class ListResponse(BaseModel):
    count: float | None = None
    data: list[dict[str, Any]] | None = None


class MetricsBatchResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    count: float
    data: list[MetricsResponse]


class HistoryRow(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    market_date: date_aliased | None = None
    spot_price: float | None = None
    call_volume: float | None = None
    put_volume: float | None = None
    call_oi: float | None = None
    put_oi: float | None = None
    put_call_ratio: float | None = None
    atm_iv: float | None = Field(
        None, description='Generic ATM IV (all expirations blended).'
    )
    atm_iv_7d: float | None = Field(
        None,
        description='7-day tenor ATM IV — closest persisted proxy to event-week vol around earnings.',
    )
    atm_iv_30d: float | None = None
    volume_oi_ratio: float | None = None


class HistoryResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    symbol: str | None = None
    count: float | None = None
    data: list[HistoryRow] | None = None


class HealthResponse(BaseModel):
    status: str | None = Field(None, examples=['ok'])
    service: str | None = Field(None, examples=['data-api'])
    version: str | None = Field(None, examples=['v1'])
    uptime: float | None = Field(None, examples=[12345.67])
    timestamp: AwareDatetime | None = None


class Issue(BaseModel):
    path: list[Any] | None = None
    message: str | None = None
    code: str | None = None


class ValidationError(BaseModel):
    error: str = Field(..., examples=['Validation failed'])
    issues: list[Issue] | None = None


class AuthError(BaseModel):
    error: str = Field(..., examples=['API key required'])
    message: str | None = Field(
        None,
        examples=[
            'Provide an API key via Authorization: Bearer oas_live_... or X-API-Key header'
        ],
    )


class RequiredScope(Enum):
    compute = 'compute'
    data = 'data'
    streaming = 'streaming'


class ScopeError(BaseModel):
    error: str = Field(..., examples=['Insufficient API key scope'])
    requiredScope: RequiredScope | None = None


class RateLimitError(BaseModel):
    error: str = Field(..., examples=['Rate limit exceeded'])
    limit: float = Field(..., examples=[120])
    retryAfter: float | None = Field(
        None, description='Seconds until rate limit resets', examples=[42]
    )


class Scope(Enum):
    day = 'day'


class CalibrationQuotaError(BaseModel):
    error: str = Field(..., examples=['Daily calibration quota exceeded'])
    code: str = Field(..., examples=['CALIBRATION_QUOTA_EXCEEDED'])
    scope: Scope = Field(..., description='Which quota window was exceeded')
    limit: float = Field(..., description='Hard cap for the scope (500 per day)')
    used: float = Field(
        ...,
        description='Number of successful calibrations the user has made in the scope window',
    )
    resetsAt: AwareDatetime = Field(
        ..., description='ISO 8601 timestamp when the quota window resets (UTC)'
    )


class NotFoundError(BaseModel):
    error: str = Field(..., examples=['No data found for this symbol'])


class InternalError(BaseModel):
    error: str = Field(..., examples=['Internal server error'])


class ServiceUnavailableError(BaseModel):
    error: str = Field(..., examples=['Worker pool draining; service unavailable'])
    code: str | None = Field(None, examples=['WORKER_POOL_UNAVAILABLE'])


class FieldSchema0(RootModel[Any]):
    root: Any


class PriceRequest1(BaseModel):
    model: Model | None = 'bs'
    isCall: bool
    K: PositiveFloat
    S: PositiveFloat | None = None
    r: float | None = None
    q: float | None = None
    sigma: confloat(ge=0.0) | None = None
    t: confloat(ge=0.0)
    symbol: constr(min_length=1, max_length=10) | None = None
    expiry: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    expiration: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    resolve: Resolve | None = Field(
        {
            'spot': True,
            'sigma': True,
            'sigmaSource': 'auto',
            'dividend': True,
            'rate': True,
            'rateMode': 'matched',
            'tenor': True,
            'spotSource': 'snapshot',
            'calibration': False,
        },
        validate_default=True,
    )
    modelParams: dict[str, FieldSchema0] | None = None
    calibrationId: str | None = None
    steps: conint(ge=10, le=5000) | None = 200
    isAmerican: bool | None = False
    detail: Detail | None = None
    histogramBins: conint(ge=2, le=200) | None = None


class PriceRequest2(BaseModel):
    model: Model | None = 'bs'
    isCall: bool
    K: PositiveFloat
    S: PositiveFloat | None = None
    r: float | None = None
    q: float | None = None
    sigma: confloat(ge=0.0) | None = None
    t: confloat(ge=0.0) | None = None
    symbol: constr(min_length=1, max_length=10) | None = None
    expiry: constr(pattern=r'^\d{4}-\d{2}-\d{2}$')
    expiration: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    resolve: Resolve1 | None = Field(
        {
            'spot': True,
            'sigma': True,
            'sigmaSource': 'auto',
            'dividend': True,
            'rate': True,
            'rateMode': 'matched',
            'tenor': True,
            'spotSource': 'snapshot',
            'calibration': False,
        },
        validate_default=True,
    )
    modelParams: dict[str, FieldSchema0] | None = None
    calibrationId: str | None = None
    steps: conint(ge=10, le=5000) | None = 200
    isAmerican: bool | None = False
    detail: Detail | None = None
    histogramBins: conint(ge=2, le=200) | None = None


class PriceRequest3(BaseModel):
    model: Model | None = 'bs'
    isCall: bool
    K: PositiveFloat
    S: PositiveFloat | None = None
    r: float | None = None
    q: float | None = None
    sigma: confloat(ge=0.0) | None = None
    t: confloat(ge=0.0) | None = None
    symbol: constr(min_length=1, max_length=10) | None = None
    expiry: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    expiration: constr(pattern=r'^\d{4}-\d{2}-\d{2}$')
    resolve: Resolve2 | None = Field(
        {
            'spot': True,
            'sigma': True,
            'sigmaSource': 'auto',
            'dividend': True,
            'rate': True,
            'rateMode': 'matched',
            'tenor': True,
            'spotSource': 'snapshot',
            'calibration': False,
        },
        validate_default=True,
    )
    modelParams: dict[str, FieldSchema0] | None = None
    calibrationId: str | None = None
    steps: conint(ge=10, le=5000) | None = 200
    isAmerican: bool | None = False
    detail: Detail | None = None
    histogramBins: conint(ge=2, le=200) | None = None


class PriceRequest(RootModel[PriceRequest1 | PriceRequest2 | PriceRequest3]):
    root: PriceRequest1 | PriceRequest2 | PriceRequest3


class GreeksRequest1(BaseModel):
    model: Model | None = 'bs'
    isCall: bool
    K: PositiveFloat
    S: PositiveFloat | None = None
    r: float | None = None
    q: float | None = None
    sigma: confloat(ge=0.0) | None = None
    t: confloat(ge=0.0)
    symbol: constr(min_length=1, max_length=10) | None = None
    expiry: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    expiration: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    resolve: Resolve3 | None = Field(
        {
            'spot': True,
            'sigma': True,
            'sigmaSource': 'auto',
            'dividend': True,
            'rate': True,
            'rateMode': 'matched',
            'tenor': True,
            'spotSource': 'snapshot',
            'calibration': False,
        },
        validate_default=True,
    )
    modelParams: dict[str, FieldSchema0] | None = None
    calibrationId: str | None = None
    includeInsight: bool | None = False
    steps: conint(ge=10, le=5000) | None = 200
    isAmerican: bool | None = False


class GreeksRequest2(BaseModel):
    model: Model | None = 'bs'
    isCall: bool
    K: PositiveFloat
    S: PositiveFloat | None = None
    r: float | None = None
    q: float | None = None
    sigma: confloat(ge=0.0) | None = None
    t: confloat(ge=0.0) | None = None
    symbol: constr(min_length=1, max_length=10) | None = None
    expiry: constr(pattern=r'^\d{4}-\d{2}-\d{2}$')
    expiration: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    resolve: Resolve4 | None = Field(
        {
            'spot': True,
            'sigma': True,
            'sigmaSource': 'auto',
            'dividend': True,
            'rate': True,
            'rateMode': 'matched',
            'tenor': True,
            'spotSource': 'snapshot',
            'calibration': False,
        },
        validate_default=True,
    )
    modelParams: dict[str, FieldSchema0] | None = None
    calibrationId: str | None = None
    includeInsight: bool | None = False
    steps: conint(ge=10, le=5000) | None = 200
    isAmerican: bool | None = False


class GreeksRequest3(BaseModel):
    model: Model | None = 'bs'
    isCall: bool
    K: PositiveFloat
    S: PositiveFloat | None = None
    r: float | None = None
    q: float | None = None
    sigma: confloat(ge=0.0) | None = None
    t: confloat(ge=0.0) | None = None
    symbol: constr(min_length=1, max_length=10) | None = None
    expiry: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') | None = None
    expiration: constr(pattern=r'^\d{4}-\d{2}-\d{2}$')
    resolve: Resolve5 | None = Field(
        {
            'spot': True,
            'sigma': True,
            'sigmaSource': 'auto',
            'dividend': True,
            'rate': True,
            'rateMode': 'matched',
            'tenor': True,
            'spotSource': 'snapshot',
            'calibration': False,
        },
        validate_default=True,
    )
    modelParams: dict[str, FieldSchema0] | None = None
    calibrationId: str | None = None
    includeInsight: bool | None = False
    steps: conint(ge=10, le=5000) | None = 200
    isAmerican: bool | None = False


class GreeksRequest(RootModel[GreeksRequest1 | GreeksRequest2 | GreeksRequest3]):
    root: GreeksRequest1 | GreeksRequest2 | GreeksRequest3


class SensitivityRequest(BaseModel):
    isCall: bool
    S: PositiveFloat
    K: PositiveFloat
    r: float
    q: float | None = 0
    sigma: confloat(ge=0.0)
    t: confloat(ge=0.0)
    axis: Axis
    points: conint(ge=5, le=200) | None = 50
    spotMin: PositiveFloat | None = None
    spotMax: PositiveFloat | None = None
    daysToExpiry: PositiveFloat | None = None
    volMin: confloat(ge=0.0) | None = None
    volMax: PositiveFloat | None = None
    model: Model6 | None = 'bs'
    modelParams: dict[str, FieldSchema0] | None = None
    greeks: list[str] | None = Field(None, max_length=20)


class PriceResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    price: float = Field(..., description='Theoretical option price')
    model: str = Field(
        ..., description='Pricing model name (e.g. "Black-Scholes-Merton")'
    )
    inputs: ResolvedInputs
    greeks: dict[str, float] | None = Field(
        None,
        description='Per-Greek values produced as a side effect of pricing for some models (binomial returns delta/gamma; PDE production path returns delta/gamma/vega/theta/rho). Use /v1/compute/greeks for the full 17-Greek response across all models.',
    )
    mcStats: McStats | None = None
    distribution: McDistribution | None = None
    fullPaths: list[list[float]] | None = Field(
        None,
        description='Raw simulated paths. Present only when `model: "mc"` and `detail: "full"`. Subsampled uniformly to satisfy two server-enforced caps: a max path count (default 1,000,000) and a max total numbers serialized (default 5,000,000). `fullPathsTruncated: true` flags when subsampling ran.',
    )
    fullPathsTruncated: bool | None = Field(
        None,
        description='True when the response was uniformly subsampled because the simulated path count exceeded the cap.',
    )
    resolved: ResolvedSummary | None = None
    warnings: list[str] | None = Field(
        None, description='Resolution warnings emitted during ticker auto-fill'
    )


class SensitivityPoint(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    x: float = Field(..., description='Sweep variable value at this point.')
    price: float | None = None
    delta: float | None = None
    gamma: float | None = None
    vega: float | None = None
    theta: float | None = None
    rho: float | None = None
    epsilon: float | None = None
    vanna: float | None = None
    charm: float | None = None
    vomma: float | None = None
    veta: float | None = None
    speed: float | None = None
    zomma: float | None = None
    color: float | None = None
    ultima: float | None = None
    lambda_: float | None = Field(None, alias='lambda')
    phi: float | None = None
    dcharmDvol: float | None = None
    modelGreeks: HestonModelGreeks | None = None


class FitDiagnostics(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    residuals: list[FitResidual] = Field(
        ...,
        description='Per-option residuals (model price − market mid). Capped at 100, sorted by descending |residual| so the worst fits survive the cap.',
    )
    bucketRmse: BucketRmse = Field(
        ...,
        description='RMSE of price residuals within each moneyness bucket. Null when the bucket has no eligible options.',
    )
    bucketCount: BucketCount = Field(
        ...,
        description='Number of options included in each moneyness bucket, mirrors `bucketRmse`.',
    )
    worstFitOption: FitResidual | None = Field(
        None,
        description='Single worst-fitting option in absolute residual terms. Null if no options were re-priceable.',
    )


class IVSurfaceResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    ticker: str = Field(
        ..., description='Underlying symbol echoed from the request (uppercased).'
    )
    date: date_aliased = Field(
        ..., description='Market date the surface snapshot applies to.'
    )
    spotPrice: float = Field(
        ..., description='Spot price observed for this surface, in dollars.'
    )
    expirations: list[date_aliased] = Field(
        ..., description='Sorted list of distinct expiration dates present in `data`.'
    )
    rowCount: int = Field(
        ..., description='Number of strike × expiration rows returned.'
    )
    data: list[IVSurfacePoint]


class SensitivityResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    axis: Axis
    model: Model8 = Field(..., description='Model used for the sweep.')
    data: list[SensitivityPoint]


class CalibrateResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
    )
    model: str
    symbol: str
    expiration: str
    params: dict[str, float | str]
    fitError: FitError
    fitDiagnostics: FitDiagnostics | None = None
    calibrationTimeMs: float
    calibrationId: str
    provider: str
