from __future__ import annotations

from pathlib import Path

from scripts import gen_models


def test_environment_path_is_the_default_local_input(monkeypatch) -> None:
    monkeypatch.setenv("OAS_OPENAPI_PATH", "/tmp/local-openapi.json")

    args = gen_models.parse_args([])

    assert args.input == "/tmp/local-openapi.json"


def test_generated_header_is_stable_across_input_names_and_run_times(tmp_path: Path) -> None:
    output = tmp_path / "models.py"
    output.write_text(
        "# generated by datamodel-codegen:\n"
        "#   filename: random-build-file.json\n"
        "#   timestamp: 2026-08-04T02:40:53+00:00\n"
        "\n"
        "from __future__ import annotations\n"
    )

    gen_models.normalize_generated_header(output)

    assert output.read_text() == (
        "# generated by datamodel-codegen:\n"
        "#   filename: openapi.json\n"
        "\n"
        "from __future__ import annotations\n"
    )
